
-- BRANCH VALUES: Use lowercase abbreviations ONLY
-- army, navy, usaf, usmc, uscg, ussf, general
-- NEVER use full names like 'Coast Guard' or 'Air Force'
-- Domain context values (logistics, intelligence, cyber, etc.) are also valid
-- Run validate-branch-values.sh before pasting into Supabase

INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Naval Navigation', '{"Maritime Navigation","Chart Reading","Celestial Navigation","ECDIS"}', 'Defense', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Ship Handling', '{"Vessel Operations","Bridge Watch","Seamanship","Helm Operations"}', 'Defense', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Submarine Operations', '{"Undersea Warfare","Nuclear Submarine","Silent Service","Submarine Systems"}', 'Defense', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Amphibious Operations', '{"Beach Operations","Landing Craft","Ship-to-Shore","Expeditionary Operations"}', 'Defense', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Airborne Operations', '{"Parachute Operations","Air Assault","Airborne Planning","Drop Zone Operations"}', 'Defense', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Artillery Fire Direction', '{"Ballistic Computation","Fire Control","Targeting Systems","Precision Munitions"}', 'Defense', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Tank Operations', '{"Armored Vehicle Operations","Combined Arms Maneuver","Gunnery","Mounted Operations"}', 'Defense', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Mine Warfare', '{"Explosive Ordnance","Mine Countermeasures","UXO","Demining"}', 'Defense', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('PMP Preparation', '{"Project Management Professional","PMP","PMBOK","Project Management Institute"}', 'Consulting', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('CISSP Knowledge', '{"CISSP","Information Systems Security","ISC2","Security Architecture"}', 'Technology', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('CompTIA Certifications', '{"CompTIA Security+","CompTIA Network+","CompTIA A+","IT Certification"}', 'Technology', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Six Sigma Methodology', '{"Lean Six Sigma","Green Belt","Black Belt","DMAIC","Process Improvement"}', 'Manufacturing', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Acquisition Certifications', '{"DAWIA","Defense Acquisition","Program Management","Level III Certified"}', 'Defense', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Safety Certifications', '{"OSHA 30","CSP","ASP","Safety Professional","BCSP"}', 'Manufacturing', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Healthcare Certifications', '{"BLS","ACLS","PALS","TCCC","EMT Certification"}', 'Healthcare', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Logistics Certifications', '{"APICS","CSCP","CPIM","Supply Chain Certification"}', 'Logistics', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Cultural Awareness', '{"Cross-Cultural Communication","Global Mindset","Cultural Competency","Diversity Awareness"}', 'General', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Conflict Resolution', '{"Mediation","Dispute Resolution","Negotiation","Conflict Management"}', 'General', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Stress Management', '{"Resilience","Emotional Intelligence","Self-Regulation","Mindfulness"}', 'General', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Self-Discipline', '{"Self-Motivation","Self-Starter","Initiative","Personal Accountability"}', 'General', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Mission Focus', '{"Goal Orientation","Results-Driven","Outcome Focus","Achievement Motivation"}', 'General', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Followership', '{"Organizational Support","Team Player","Execution","Operational Support"}', 'General', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Physical Fitness', '{"Health Conscious","Active Lifestyle","Physical Endurance","Wellness Advocate"}', 'General', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Military Bearing', '{"Professional Presence","Executive Presence","Professional Demeanor","Poise"}', 'General', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('SCADA Systems', '{"Industrial Control Systems","ICS Security","SCADA Operations","OT Security"}', 'Energy', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Blockchain Knowledge', '{"Distributed Ledger","Smart Contracts","Cryptocurrency","Web3"}', 'Technology', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Machine Learning', '{"AI/ML","Deep Learning","Neural Networks","Predictive Modeling","TensorFlow"}', 'Technology', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('IoT Systems', '{"Internet of Things","Sensor Networks","Edge Computing","Embedded Systems"}', 'Technology', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('DevSecOps', '{"Secure Development","CI/CD Security","Container Security","Application Security"}', 'Technology', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('ERP Systems', '{"SAP","Oracle ERP","Enterprise Resource Planning","Business Applications"}', 'Technology', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Backup and Recovery', '{"Disaster Recovery","Business Continuity","Data Backup","RTO/RPO"}', 'Technology', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Identity Management', '{"IAM","Single Sign-On","MFA","Privileged Access Management","Okta"}', 'Technology', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Real Estate Management', '{"Property Management","Facility Operations","Lease Administration","Space Planning"}', 'Construction', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Fleet Electrification', '{"EV Fleet","Electric Vehicle Infrastructure","Charging Stations","Green Fleet"}', 'Logistics', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Regulatory Compliance', '{"FDA Compliance","EPA Compliance","SOX Compliance","Regulatory Affairs"}', 'General', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Vendor Management', '{"Supplier Relationship Management","RFP Management","Vendor Evaluation","Contract Negotiation"}', 'General', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Business Development', '{"Sales Strategy","Client Acquisition","Proposal Writing","Capture Management"}', 'Defense', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Capture Management', '{"Proposal Development","Win Strategy","Government BD","Opportunity Pipeline"}', 'Defense', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_linkedin_keywords (military_skill, linkedin_keywords, industry, priority) VALUES ('Technical Proposal Writing', '{"RFP Response","Technical Volume","Proposal Coordination","Orals Presentations"}', 'Defense', 'high') ON CONFLICT DO NOTHING;

-- dict_linkedin_keywords (final): 39 INSERT statements