-- Supply Chain patterns (extra)

-- BRANCH VALUES: Use lowercase abbreviations ONLY
-- army, navy, usaf, usmc, uscg, ussf, general
-- NEVER use full names like 'Coast Guard' or 'Air Force'
-- Domain context values (logistics, intelligence, cyber, etc.) are also valid
-- Run validate-branch-values.sh before pasting into Supabase

INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('supply_chain_junior_enlisted_extra_1', 'Supply Chain', 'junior_enlisted', '{action_verb} end-to-end supply chain for {count}+ SKUs valued at ${value}, achieving {metric}% fill rate', 'Managed end-to-end supply chain for 5,000+ NSNs valued at $30M, achieving 97% fill rate', 'Managed end-to-end supply chain for 5,000+ SKUs valued at $30M, achieving 97% fill rate', '{"action_verb","count","value","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('supply_chain_junior_enlisted_extra_2', 'Supply Chain', 'junior_enlisted', 'Negotiated {count} vendor contracts saving ${savings} annually while maintaining {metric}% quality standards', 'Negotiated 25 supply contracts saving $500K annually while maintaining 99% quality standards', 'Negotiated 25 vendor contracts saving $500K annually while maintaining 99% quality standards', '{"count","savings","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('supply_chain_senior_enlisted_extra_1', 'Supply Chain', 'senior_enlisted', '{action_verb} end-to-end supply chain for {count}+ SKUs valued at ${value}, achieving {metric}% fill rate', 'Managed end-to-end supply chain for 5,000+ NSNs valued at $30M, achieving 97% fill rate', 'Managed end-to-end supply chain for 5,000+ SKUs valued at $30M, achieving 97% fill rate', '{"action_verb","count","value","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('supply_chain_senior_enlisted_extra_2', 'Supply Chain', 'senior_enlisted', 'Negotiated {count} vendor contracts saving ${savings} annually while maintaining {metric}% quality standards', 'Negotiated 25 supply contracts saving $500K annually while maintaining 99% quality standards', 'Negotiated 25 vendor contracts saving $500K annually while maintaining 99% quality standards', '{"count","savings","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('supply_chain_junior_officer_extra_1', 'Supply Chain', 'junior_officer', '{action_verb} end-to-end supply chain for {count}+ SKUs valued at ${value}, achieving {metric}% fill rate', 'Managed end-to-end supply chain for 5,000+ NSNs valued at $30M, achieving 97% fill rate', 'Managed end-to-end supply chain for 5,000+ SKUs valued at $30M, achieving 97% fill rate', '{"action_verb","count","value","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('supply_chain_junior_officer_extra_2', 'Supply Chain', 'junior_officer', 'Negotiated {count} vendor contracts saving ${savings} annually while maintaining {metric}% quality standards', 'Negotiated 25 supply contracts saving $500K annually while maintaining 99% quality standards', 'Negotiated 25 vendor contracts saving $500K annually while maintaining 99% quality standards', '{"count","savings","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('supply_chain_senior_officer_extra_1', 'Supply Chain', 'senior_officer', '{action_verb} end-to-end supply chain for {count}+ SKUs valued at ${value}, achieving {metric}% fill rate', 'Managed end-to-end supply chain for 5,000+ NSNs valued at $30M, achieving 97% fill rate', 'Managed end-to-end supply chain for 5,000+ SKUs valued at $30M, achieving 97% fill rate', '{"action_verb","count","value","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('supply_chain_senior_officer_extra_2', 'Supply Chain', 'senior_officer', 'Negotiated {count} vendor contracts saving ${savings} annually while maintaining {metric}% quality standards', 'Negotiated 25 supply contracts saving $500K annually while maintaining 99% quality standards', 'Negotiated 25 vendor contracts saving $500K annually while maintaining 99% quality standards', '{"count","savings","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('supply_chain_warrant_officer_extra_1', 'Supply Chain', 'warrant_officer', '{action_verb} end-to-end supply chain for {count}+ SKUs valued at ${value}, achieving {metric}% fill rate', 'Managed end-to-end supply chain for 5,000+ NSNs valued at $30M, achieving 97% fill rate', 'Managed end-to-end supply chain for 5,000+ SKUs valued at $30M, achieving 97% fill rate', '{"action_verb","count","value","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('supply_chain_warrant_officer_extra_2', 'Supply Chain', 'warrant_officer', 'Negotiated {count} vendor contracts saving ${savings} annually while maintaining {metric}% quality standards', 'Negotiated 25 supply contracts saving $500K annually while maintaining 99% quality standards', 'Negotiated 25 vendor contracts saving $500K annually while maintaining 99% quality standards', '{"count","savings","metric"}', '{}') ON CONFLICT DO NOTHING;

-- Human Resources patterns (extra)
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('human_resources_junior_enlisted_extra_1', 'Human Resources', 'junior_enlisted', '{action_verb} {process_type} for {count}+ employees, reducing {metric} by {percentage}%', 'Managed in-processing for 200+ new soldiers per quarter, reducing onboarding time by 30%', 'Managed onboarding process for 200+ new hires per quarter, reducing time-to-productivity by 30%', '{"action_verb","process_type","count","metric","percentage"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('human_resources_junior_enlisted_extra_2', 'Human Resources', 'junior_enlisted', 'Conducted {count} performance evaluations per {timeframe}, achieving {metric}% on-time completion', 'Conducted 100 NCOERs per quarter, achieving 100% on-time submission', 'Conducted 100 performance reviews per quarter, achieving 100% on-time completion', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('human_resources_senior_enlisted_extra_1', 'Human Resources', 'senior_enlisted', '{action_verb} {process_type} for {count}+ employees, reducing {metric} by {percentage}%', 'Managed in-processing for 200+ new soldiers per quarter, reducing onboarding time by 30%', 'Managed onboarding process for 200+ new hires per quarter, reducing time-to-productivity by 30%', '{"action_verb","process_type","count","metric","percentage"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('human_resources_senior_enlisted_extra_2', 'Human Resources', 'senior_enlisted', 'Conducted {count} performance evaluations per {timeframe}, achieving {metric}% on-time completion', 'Conducted 100 NCOERs per quarter, achieving 100% on-time submission', 'Conducted 100 performance reviews per quarter, achieving 100% on-time completion', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('human_resources_junior_officer_extra_1', 'Human Resources', 'junior_officer', '{action_verb} {process_type} for {count}+ employees, reducing {metric} by {percentage}%', 'Managed in-processing for 200+ new soldiers per quarter, reducing onboarding time by 30%', 'Managed onboarding process for 200+ new hires per quarter, reducing time-to-productivity by 30%', '{"action_verb","process_type","count","metric","percentage"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('human_resources_junior_officer_extra_2', 'Human Resources', 'junior_officer', 'Conducted {count} performance evaluations per {timeframe}, achieving {metric}% on-time completion', 'Conducted 100 NCOERs per quarter, achieving 100% on-time submission', 'Conducted 100 performance reviews per quarter, achieving 100% on-time completion', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('human_resources_senior_officer_extra_1', 'Human Resources', 'senior_officer', '{action_verb} {process_type} for {count}+ employees, reducing {metric} by {percentage}%', 'Managed in-processing for 200+ new soldiers per quarter, reducing onboarding time by 30%', 'Managed onboarding process for 200+ new hires per quarter, reducing time-to-productivity by 30%', '{"action_verb","process_type","count","metric","percentage"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('human_resources_senior_officer_extra_2', 'Human Resources', 'senior_officer', 'Conducted {count} performance evaluations per {timeframe}, achieving {metric}% on-time completion', 'Conducted 100 NCOERs per quarter, achieving 100% on-time submission', 'Conducted 100 performance reviews per quarter, achieving 100% on-time completion', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('human_resources_warrant_officer_extra_1', 'Human Resources', 'warrant_officer', '{action_verb} {process_type} for {count}+ employees, reducing {metric} by {percentage}%', 'Managed in-processing for 200+ new soldiers per quarter, reducing onboarding time by 30%', 'Managed onboarding process for 200+ new hires per quarter, reducing time-to-productivity by 30%', '{"action_verb","process_type","count","metric","percentage"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('human_resources_warrant_officer_extra_2', 'Human Resources', 'warrant_officer', 'Conducted {count} performance evaluations per {timeframe}, achieving {metric}% on-time completion', 'Conducted 100 NCOERs per quarter, achieving 100% on-time submission', 'Conducted 100 performance reviews per quarter, achieving 100% on-time completion', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;

-- Cybersecurity patterns (extra)
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('cybersecurity_junior_enlisted_extra_1', 'Cybersecurity', 'junior_enlisted', '{action_verb} security posture for {scope} network, reducing vulnerabilities by {percentage}%', 'Hardened security posture for battalion network of 500+ endpoints, reducing vulnerabilities by 85%', 'Strengthened security posture for enterprise network of 500+ endpoints, reducing vulnerabilities by 85%', '{"action_verb","scope","percentage"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('cybersecurity_junior_enlisted_extra_2', 'Cybersecurity', 'junior_enlisted', 'Responded to {count} security incidents per {timeframe}, achieving {metric} mean time to resolution', 'Responded to 50 security incidents per month, achieving 4-hour mean time to resolution', 'Responded to 50 security incidents per month, achieving 4-hour mean time to resolution', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('cybersecurity_senior_enlisted_extra_1', 'Cybersecurity', 'senior_enlisted', '{action_verb} security posture for {scope} network, reducing vulnerabilities by {percentage}%', 'Hardened security posture for battalion network of 500+ endpoints, reducing vulnerabilities by 85%', 'Strengthened security posture for enterprise network of 500+ endpoints, reducing vulnerabilities by 85%', '{"action_verb","scope","percentage"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('cybersecurity_senior_enlisted_extra_2', 'Cybersecurity', 'senior_enlisted', 'Responded to {count} security incidents per {timeframe}, achieving {metric} mean time to resolution', 'Responded to 50 security incidents per month, achieving 4-hour mean time to resolution', 'Responded to 50 security incidents per month, achieving 4-hour mean time to resolution', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('cybersecurity_junior_officer_extra_1', 'Cybersecurity', 'junior_officer', '{action_verb} security posture for {scope} network, reducing vulnerabilities by {percentage}%', 'Hardened security posture for battalion network of 500+ endpoints, reducing vulnerabilities by 85%', 'Strengthened security posture for enterprise network of 500+ endpoints, reducing vulnerabilities by 85%', '{"action_verb","scope","percentage"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('cybersecurity_junior_officer_extra_2', 'Cybersecurity', 'junior_officer', 'Responded to {count} security incidents per {timeframe}, achieving {metric} mean time to resolution', 'Responded to 50 security incidents per month, achieving 4-hour mean time to resolution', 'Responded to 50 security incidents per month, achieving 4-hour mean time to resolution', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('cybersecurity_senior_officer_extra_1', 'Cybersecurity', 'senior_officer', '{action_verb} security posture for {scope} network, reducing vulnerabilities by {percentage}%', 'Hardened security posture for battalion network of 500+ endpoints, reducing vulnerabilities by 85%', 'Strengthened security posture for enterprise network of 500+ endpoints, reducing vulnerabilities by 85%', '{"action_verb","scope","percentage"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('cybersecurity_senior_officer_extra_2', 'Cybersecurity', 'senior_officer', 'Responded to {count} security incidents per {timeframe}, achieving {metric} mean time to resolution', 'Responded to 50 security incidents per month, achieving 4-hour mean time to resolution', 'Responded to 50 security incidents per month, achieving 4-hour mean time to resolution', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('cybersecurity_warrant_officer_extra_1', 'Cybersecurity', 'warrant_officer', '{action_verb} security posture for {scope} network, reducing vulnerabilities by {percentage}%', 'Hardened security posture for battalion network of 500+ endpoints, reducing vulnerabilities by 85%', 'Strengthened security posture for enterprise network of 500+ endpoints, reducing vulnerabilities by 85%', '{"action_verb","scope","percentage"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('cybersecurity_warrant_officer_extra_2', 'Cybersecurity', 'warrant_officer', 'Responded to {count} security incidents per {timeframe}, achieving {metric} mean time to resolution', 'Responded to 50 security incidents per month, achieving 4-hour mean time to resolution', 'Responded to 50 security incidents per month, achieving 4-hour mean time to resolution', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;

-- Emergency Response patterns (extra)
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('emergency_response_junior_enlisted_extra_1', 'Emergency Response', 'junior_enlisted', '{action_verb} emergency response plan for {scope}, tested through {count} exercises achieving {metric}', 'Developed mass casualty response plan for 2,000-person installation, tested through 6 drills achieving full compliance', 'Developed emergency response plan for 2,000-person facility, tested through 6 exercises achieving full compliance', '{"action_verb","scope","count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('emergency_response_junior_enlisted_extra_2', 'Emergency Response', 'junior_enlisted', 'Led {count}-person response team during {event_type}, coordinating {resource_type} across {scope}', 'Led 20-person response team during base flooding, coordinating evacuation of 500 personnel across 3 buildings', 'Led 20-person response team during facility emergency, coordinating evacuation of 500 personnel across 3 buildings', '{"count","event_type","resource_type","scope"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('emergency_response_senior_enlisted_extra_1', 'Emergency Response', 'senior_enlisted', '{action_verb} emergency response plan for {scope}, tested through {count} exercises achieving {metric}', 'Developed mass casualty response plan for 2,000-person installation, tested through 6 drills achieving full compliance', 'Developed emergency response plan for 2,000-person facility, tested through 6 exercises achieving full compliance', '{"action_verb","scope","count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('emergency_response_senior_enlisted_extra_2', 'Emergency Response', 'senior_enlisted', 'Led {count}-person response team during {event_type}, coordinating {resource_type} across {scope}', 'Led 20-person response team during base flooding, coordinating evacuation of 500 personnel across 3 buildings', 'Led 20-person response team during facility emergency, coordinating evacuation of 500 personnel across 3 buildings', '{"count","event_type","resource_type","scope"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('emergency_response_junior_officer_extra_1', 'Emergency Response', 'junior_officer', '{action_verb} emergency response plan for {scope}, tested through {count} exercises achieving {metric}', 'Developed mass casualty response plan for 2,000-person installation, tested through 6 drills achieving full compliance', 'Developed emergency response plan for 2,000-person facility, tested through 6 exercises achieving full compliance', '{"action_verb","scope","count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('emergency_response_junior_officer_extra_2', 'Emergency Response', 'junior_officer', 'Led {count}-person response team during {event_type}, coordinating {resource_type} across {scope}', 'Led 20-person response team during base flooding, coordinating evacuation of 500 personnel across 3 buildings', 'Led 20-person response team during facility emergency, coordinating evacuation of 500 personnel across 3 buildings', '{"count","event_type","resource_type","scope"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('emergency_response_senior_officer_extra_1', 'Emergency Response', 'senior_officer', '{action_verb} emergency response plan for {scope}, tested through {count} exercises achieving {metric}', 'Developed mass casualty response plan for 2,000-person installation, tested through 6 drills achieving full compliance', 'Developed emergency response plan for 2,000-person facility, tested through 6 exercises achieving full compliance', '{"action_verb","scope","count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('emergency_response_senior_officer_extra_2', 'Emergency Response', 'senior_officer', 'Led {count}-person response team during {event_type}, coordinating {resource_type} across {scope}', 'Led 20-person response team during base flooding, coordinating evacuation of 500 personnel across 3 buildings', 'Led 20-person response team during facility emergency, coordinating evacuation of 500 personnel across 3 buildings', '{"count","event_type","resource_type","scope"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('emergency_response_warrant_officer_extra_1', 'Emergency Response', 'warrant_officer', '{action_verb} emergency response plan for {scope}, tested through {count} exercises achieving {metric}', 'Developed mass casualty response plan for 2,000-person installation, tested through 6 drills achieving full compliance', 'Developed emergency response plan for 2,000-person facility, tested through 6 exercises achieving full compliance', '{"action_verb","scope","count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('emergency_response_warrant_officer_extra_2', 'Emergency Response', 'warrant_officer', 'Led {count}-person response team during {event_type}, coordinating {resource_type} across {scope}', 'Led 20-person response team during base flooding, coordinating evacuation of 500 personnel across 3 buildings', 'Led 20-person response team during facility emergency, coordinating evacuation of 500 personnel across 3 buildings', '{"count","event_type","resource_type","scope"}', '{}') ON CONFLICT DO NOTHING;

-- Strategic Planning patterns (extra)
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('strategic_planning_junior_enlisted_extra_1', 'Strategic Planning', 'junior_enlisted', '{action_verb} {plan_type} plan spanning {timeframe}, aligning {count} departments toward {objective}', 'Developed 5-year modernization plan spanning FY24-28, aligning 8 directorates toward force readiness goals', 'Developed 5-year strategic plan spanning FY24-28, aligning 8 departments toward growth objectives', '{"action_verb","plan_type","timeframe","count","objective"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('strategic_planning_junior_enlisted_extra_2', 'Strategic Planning', 'junior_enlisted', 'Identified and prioritized {count} strategic initiatives, securing ${funding} in resources for implementation', 'Identified and prioritized 12 capability gaps, securing $5M in MILCON funding for facility upgrades', 'Identified and prioritized 12 strategic initiatives, securing $5M in capital investment for implementation', '{"count","funding"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('strategic_planning_senior_enlisted_extra_1', 'Strategic Planning', 'senior_enlisted', '{action_verb} {plan_type} plan spanning {timeframe}, aligning {count} departments toward {objective}', 'Developed 5-year modernization plan spanning FY24-28, aligning 8 directorates toward force readiness goals', 'Developed 5-year strategic plan spanning FY24-28, aligning 8 departments toward growth objectives', '{"action_verb","plan_type","timeframe","count","objective"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('strategic_planning_senior_enlisted_extra_2', 'Strategic Planning', 'senior_enlisted', 'Identified and prioritized {count} strategic initiatives, securing ${funding} in resources for implementation', 'Identified and prioritized 12 capability gaps, securing $5M in MILCON funding for facility upgrades', 'Identified and prioritized 12 strategic initiatives, securing $5M in capital investment for implementation', '{"count","funding"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('strategic_planning_junior_officer_extra_1', 'Strategic Planning', 'junior_officer', '{action_verb} {plan_type} plan spanning {timeframe}, aligning {count} departments toward {objective}', 'Developed 5-year modernization plan spanning FY24-28, aligning 8 directorates toward force readiness goals', 'Developed 5-year strategic plan spanning FY24-28, aligning 8 departments toward growth objectives', '{"action_verb","plan_type","timeframe","count","objective"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('strategic_planning_junior_officer_extra_2', 'Strategic Planning', 'junior_officer', 'Identified and prioritized {count} strategic initiatives, securing ${funding} in resources for implementation', 'Identified and prioritized 12 capability gaps, securing $5M in MILCON funding for facility upgrades', 'Identified and prioritized 12 strategic initiatives, securing $5M in capital investment for implementation', '{"count","funding"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('strategic_planning_senior_officer_extra_1', 'Strategic Planning', 'senior_officer', '{action_verb} {plan_type} plan spanning {timeframe}, aligning {count} departments toward {objective}', 'Developed 5-year modernization plan spanning FY24-28, aligning 8 directorates toward force readiness goals', 'Developed 5-year strategic plan spanning FY24-28, aligning 8 departments toward growth objectives', '{"action_verb","plan_type","timeframe","count","objective"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('strategic_planning_senior_officer_extra_2', 'Strategic Planning', 'senior_officer', 'Identified and prioritized {count} strategic initiatives, securing ${funding} in resources for implementation', 'Identified and prioritized 12 capability gaps, securing $5M in MILCON funding for facility upgrades', 'Identified and prioritized 12 strategic initiatives, securing $5M in capital investment for implementation', '{"count","funding"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('strategic_planning_warrant_officer_extra_1', 'Strategic Planning', 'warrant_officer', '{action_verb} {plan_type} plan spanning {timeframe}, aligning {count} departments toward {objective}', 'Developed 5-year modernization plan spanning FY24-28, aligning 8 directorates toward force readiness goals', 'Developed 5-year strategic plan spanning FY24-28, aligning 8 departments toward growth objectives', '{"action_verb","plan_type","timeframe","count","objective"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('strategic_planning_warrant_officer_extra_2', 'Strategic Planning', 'warrant_officer', 'Identified and prioritized {count} strategic initiatives, securing ${funding} in resources for implementation', 'Identified and prioritized 12 capability gaps, securing $5M in MILCON funding for facility upgrades', 'Identified and prioritized 12 strategic initiatives, securing $5M in capital investment for implementation', '{"count","funding"}', '{}') ON CONFLICT DO NOTHING;

-- Diversity & Inclusion patterns (extra)
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('diversity___inclusion_junior_enlisted_extra_1', 'Diversity & Inclusion', 'junior_enlisted', '{action_verb} equal opportunity program serving {count} personnel, resolving {case_count} cases with {metric}% satisfaction', 'Managed EO program serving 800 soldiers, resolving 30 complaints with 95% satisfaction', 'Managed diversity and inclusion program serving 800 employees, resolving 30 cases with 95% satisfaction', '{"action_verb","count","case_count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('diversity___inclusion_senior_enlisted_extra_1', 'Diversity & Inclusion', 'senior_enlisted', '{action_verb} equal opportunity program serving {count} personnel, resolving {case_count} cases with {metric}% satisfaction', 'Managed EO program serving 800 soldiers, resolving 30 complaints with 95% satisfaction', 'Managed diversity and inclusion program serving 800 employees, resolving 30 cases with 95% satisfaction', '{"action_verb","count","case_count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('diversity___inclusion_junior_officer_extra_1', 'Diversity & Inclusion', 'junior_officer', '{action_verb} equal opportunity program serving {count} personnel, resolving {case_count} cases with {metric}% satisfaction', 'Managed EO program serving 800 soldiers, resolving 30 complaints with 95% satisfaction', 'Managed diversity and inclusion program serving 800 employees, resolving 30 cases with 95% satisfaction', '{"action_verb","count","case_count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('diversity___inclusion_senior_officer_extra_1', 'Diversity & Inclusion', 'senior_officer', '{action_verb} equal opportunity program serving {count} personnel, resolving {case_count} cases with {metric}% satisfaction', 'Managed EO program serving 800 soldiers, resolving 30 complaints with 95% satisfaction', 'Managed diversity and inclusion program serving 800 employees, resolving 30 cases with 95% satisfaction', '{"action_verb","count","case_count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('diversity___inclusion_warrant_officer_extra_1', 'Diversity & Inclusion', 'warrant_officer', '{action_verb} equal opportunity program serving {count} personnel, resolving {case_count} cases with {metric}% satisfaction', 'Managed EO program serving 800 soldiers, resolving 30 complaints with 95% satisfaction', 'Managed diversity and inclusion program serving 800 employees, resolving 30 cases with 95% satisfaction', '{"action_verb","count","case_count","metric"}', '{}') ON CONFLICT DO NOTHING;

-- Environmental patterns (extra)
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('environmental_junior_enlisted_extra_1', 'Environmental', 'junior_enlisted', '{action_verb} environmental compliance program for {scope}, achieving zero violations across {count} inspections', 'Managed environmental compliance for 500-acre installation, achieving zero violations across 12 EPA inspections', 'Managed environmental compliance program for 500-acre facility, achieving zero violations across 12 regulatory inspections', '{"action_verb","scope","count"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('environmental_junior_enlisted_extra_2', 'Environmental', 'junior_enlisted', 'Reduced {waste_type} waste by {percentage}% through {method}, saving ${savings} in disposal costs', 'Reduced hazardous waste by 40% through recycling program, saving $200K in disposal costs', 'Reduced hazardous waste by 40% through sustainability program, saving $200K in disposal costs', '{"waste_type","percentage","method","savings"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('environmental_senior_enlisted_extra_1', 'Environmental', 'senior_enlisted', '{action_verb} environmental compliance program for {scope}, achieving zero violations across {count} inspections', 'Managed environmental compliance for 500-acre installation, achieving zero violations across 12 EPA inspections', 'Managed environmental compliance program for 500-acre facility, achieving zero violations across 12 regulatory inspections', '{"action_verb","scope","count"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('environmental_senior_enlisted_extra_2', 'Environmental', 'senior_enlisted', 'Reduced {waste_type} waste by {percentage}% through {method}, saving ${savings} in disposal costs', 'Reduced hazardous waste by 40% through recycling program, saving $200K in disposal costs', 'Reduced hazardous waste by 40% through sustainability program, saving $200K in disposal costs', '{"waste_type","percentage","method","savings"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('environmental_junior_officer_extra_1', 'Environmental', 'junior_officer', '{action_verb} environmental compliance program for {scope}, achieving zero violations across {count} inspections', 'Managed environmental compliance for 500-acre installation, achieving zero violations across 12 EPA inspections', 'Managed environmental compliance program for 500-acre facility, achieving zero violations across 12 regulatory inspections', '{"action_verb","scope","count"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('environmental_junior_officer_extra_2', 'Environmental', 'junior_officer', 'Reduced {waste_type} waste by {percentage}% through {method}, saving ${savings} in disposal costs', 'Reduced hazardous waste by 40% through recycling program, saving $200K in disposal costs', 'Reduced hazardous waste by 40% through sustainability program, saving $200K in disposal costs', '{"waste_type","percentage","method","savings"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('environmental_senior_officer_extra_1', 'Environmental', 'senior_officer', '{action_verb} environmental compliance program for {scope}, achieving zero violations across {count} inspections', 'Managed environmental compliance for 500-acre installation, achieving zero violations across 12 EPA inspections', 'Managed environmental compliance program for 500-acre facility, achieving zero violations across 12 regulatory inspections', '{"action_verb","scope","count"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('environmental_senior_officer_extra_2', 'Environmental', 'senior_officer', 'Reduced {waste_type} waste by {percentage}% through {method}, saving ${savings} in disposal costs', 'Reduced hazardous waste by 40% through recycling program, saving $200K in disposal costs', 'Reduced hazardous waste by 40% through sustainability program, saving $200K in disposal costs', '{"waste_type","percentage","method","savings"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('environmental_warrant_officer_extra_1', 'Environmental', 'warrant_officer', '{action_verb} environmental compliance program for {scope}, achieving zero violations across {count} inspections', 'Managed environmental compliance for 500-acre installation, achieving zero violations across 12 EPA inspections', 'Managed environmental compliance program for 500-acre facility, achieving zero violations across 12 regulatory inspections', '{"action_verb","scope","count"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('environmental_warrant_officer_extra_2', 'Environmental', 'warrant_officer', 'Reduced {waste_type} waste by {percentage}% through {method}, saving ${savings} in disposal costs', 'Reduced hazardous waste by 40% through recycling program, saving $200K in disposal costs', 'Reduced hazardous waste by 40% through sustainability program, saving $200K in disposal costs', '{"waste_type","percentage","method","savings"}', '{}') ON CONFLICT DO NOTHING;

-- International Operations patterns (extra)
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('international_operations_junior_enlisted_extra_1', 'International Operations', 'junior_enlisted', '{action_verb} operations across {count} countries, coordinating with {partner_count} international partners', 'Coordinated intelligence operations across 5 countries, coordinating with 12 coalition partners', 'Coordinated international operations across 5 countries, coordinating with 12 international partners', '{"action_verb","count","partner_count"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('international_operations_junior_enlisted_extra_2', 'International Operations', 'junior_enlisted', 'Managed {count} foreign national employees, navigating {challenge_type} to achieve {result}', 'Managed 30 local national interpreters, navigating cultural differences to achieve mission objectives', 'Managed 30 international team members, navigating cultural differences to achieve project objectives', '{"count","challenge_type","result"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('international_operations_senior_enlisted_extra_1', 'International Operations', 'senior_enlisted', '{action_verb} operations across {count} countries, coordinating with {partner_count} international partners', 'Coordinated intelligence operations across 5 countries, coordinating with 12 coalition partners', 'Coordinated international operations across 5 countries, coordinating with 12 international partners', '{"action_verb","count","partner_count"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('international_operations_senior_enlisted_extra_2', 'International Operations', 'senior_enlisted', 'Managed {count} foreign national employees, navigating {challenge_type} to achieve {result}', 'Managed 30 local national interpreters, navigating cultural differences to achieve mission objectives', 'Managed 30 international team members, navigating cultural differences to achieve project objectives', '{"count","challenge_type","result"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('international_operations_junior_officer_extra_1', 'International Operations', 'junior_officer', '{action_verb} operations across {count} countries, coordinating with {partner_count} international partners', 'Coordinated intelligence operations across 5 countries, coordinating with 12 coalition partners', 'Coordinated international operations across 5 countries, coordinating with 12 international partners', '{"action_verb","count","partner_count"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('international_operations_junior_officer_extra_2', 'International Operations', 'junior_officer', 'Managed {count} foreign national employees, navigating {challenge_type} to achieve {result}', 'Managed 30 local national interpreters, navigating cultural differences to achieve mission objectives', 'Managed 30 international team members, navigating cultural differences to achieve project objectives', '{"count","challenge_type","result"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('international_operations_senior_officer_extra_1', 'International Operations', 'senior_officer', '{action_verb} operations across {count} countries, coordinating with {partner_count} international partners', 'Coordinated intelligence operations across 5 countries, coordinating with 12 coalition partners', 'Coordinated international operations across 5 countries, coordinating with 12 international partners', '{"action_verb","count","partner_count"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('international_operations_senior_officer_extra_2', 'International Operations', 'senior_officer', 'Managed {count} foreign national employees, navigating {challenge_type} to achieve {result}', 'Managed 30 local national interpreters, navigating cultural differences to achieve mission objectives', 'Managed 30 international team members, navigating cultural differences to achieve project objectives', '{"count","challenge_type","result"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('international_operations_warrant_officer_extra_1', 'International Operations', 'warrant_officer', '{action_verb} operations across {count} countries, coordinating with {partner_count} international partners', 'Coordinated intelligence operations across 5 countries, coordinating with 12 coalition partners', 'Coordinated international operations across 5 countries, coordinating with 12 international partners', '{"action_verb","count","partner_count"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('international_operations_warrant_officer_extra_2', 'International Operations', 'warrant_officer', 'Managed {count} foreign national employees, navigating {challenge_type} to achieve {result}', 'Managed 30 local national interpreters, navigating cultural differences to achieve mission objectives', 'Managed 30 international team members, navigating cultural differences to achieve project objectives', '{"count","challenge_type","result"}', '{}') ON CONFLICT DO NOTHING;

-- Quality Management patterns (extra)
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('quality_management_junior_enlisted_extra_1', 'Quality Management', 'junior_enlisted', '{action_verb} quality management system achieving {certification} certification for {scope}', 'Implemented quality management system achieving ISO 9001 equivalent for maintenance operations', 'Implemented quality management system achieving ISO 9001 certification for manufacturing operations', '{"action_verb","certification","scope"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('quality_management_junior_enlisted_extra_2', 'Quality Management', 'junior_enlisted', 'Reduced defect rate from {before}% to {after}% through {method}, saving ${savings} in rework costs', 'Reduced equipment failure rate from 8% to 2% through predictive maintenance, saving $300K in repair costs', 'Reduced defect rate from 8% to 2% through process improvement, saving $300K in rework costs', '{"before","after","method","savings"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('quality_management_senior_enlisted_extra_1', 'Quality Management', 'senior_enlisted', '{action_verb} quality management system achieving {certification} certification for {scope}', 'Implemented quality management system achieving ISO 9001 equivalent for maintenance operations', 'Implemented quality management system achieving ISO 9001 certification for manufacturing operations', '{"action_verb","certification","scope"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('quality_management_senior_enlisted_extra_2', 'Quality Management', 'senior_enlisted', 'Reduced defect rate from {before}% to {after}% through {method}, saving ${savings} in rework costs', 'Reduced equipment failure rate from 8% to 2% through predictive maintenance, saving $300K in repair costs', 'Reduced defect rate from 8% to 2% through process improvement, saving $300K in rework costs', '{"before","after","method","savings"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('quality_management_junior_officer_extra_1', 'Quality Management', 'junior_officer', '{action_verb} quality management system achieving {certification} certification for {scope}', 'Implemented quality management system achieving ISO 9001 equivalent for maintenance operations', 'Implemented quality management system achieving ISO 9001 certification for manufacturing operations', '{"action_verb","certification","scope"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('quality_management_junior_officer_extra_2', 'Quality Management', 'junior_officer', 'Reduced defect rate from {before}% to {after}% through {method}, saving ${savings} in rework costs', 'Reduced equipment failure rate from 8% to 2% through predictive maintenance, saving $300K in repair costs', 'Reduced defect rate from 8% to 2% through process improvement, saving $300K in rework costs', '{"before","after","method","savings"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('quality_management_senior_officer_extra_1', 'Quality Management', 'senior_officer', '{action_verb} quality management system achieving {certification} certification for {scope}', 'Implemented quality management system achieving ISO 9001 equivalent for maintenance operations', 'Implemented quality management system achieving ISO 9001 certification for manufacturing operations', '{"action_verb","certification","scope"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('quality_management_senior_officer_extra_2', 'Quality Management', 'senior_officer', 'Reduced defect rate from {before}% to {after}% through {method}, saving ${savings} in rework costs', 'Reduced equipment failure rate from 8% to 2% through predictive maintenance, saving $300K in repair costs', 'Reduced defect rate from 8% to 2% through process improvement, saving $300K in rework costs', '{"before","after","method","savings"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('quality_management_warrant_officer_extra_1', 'Quality Management', 'warrant_officer', '{action_verb} quality management system achieving {certification} certification for {scope}', 'Implemented quality management system achieving ISO 9001 equivalent for maintenance operations', 'Implemented quality management system achieving ISO 9001 certification for manufacturing operations', '{"action_verb","certification","scope"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('quality_management_warrant_officer_extra_2', 'Quality Management', 'warrant_officer', 'Reduced defect rate from {before}% to {after}% through {method}, saving ${savings} in rework costs', 'Reduced equipment failure rate from 8% to 2% through predictive maintenance, saving $300K in repair costs', 'Reduced defect rate from 8% to 2% through process improvement, saving $300K in rework costs', '{"before","after","method","savings"}', '{}') ON CONFLICT DO NOTHING;

-- Medical patterns (extra)
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('medical_junior_enlisted_extra_1', 'Medical', 'junior_enlisted', '{action_verb} medical support for {count} personnel, maintaining {metric}% medical readiness', 'Provided medical support for 500 soldiers, maintaining 97% medical readiness rate', 'Coordinated healthcare services for 500 employees, maintaining 97% health compliance rate', '{"action_verb","count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('medical_junior_enlisted_extra_2', 'Medical', 'junior_enlisted', 'Managed {count} patient encounters per {timeframe}, achieving {metric}% patient satisfaction', 'Managed 200 patient encounters per week, achieving 96% patient satisfaction scores', 'Managed 200 client interactions per week, achieving 96% satisfaction scores', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('medical_senior_enlisted_extra_1', 'Medical', 'senior_enlisted', '{action_verb} medical support for {count} personnel, maintaining {metric}% medical readiness', 'Provided medical support for 500 soldiers, maintaining 97% medical readiness rate', 'Coordinated healthcare services for 500 employees, maintaining 97% health compliance rate', '{"action_verb","count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('medical_senior_enlisted_extra_2', 'Medical', 'senior_enlisted', 'Managed {count} patient encounters per {timeframe}, achieving {metric}% patient satisfaction', 'Managed 200 patient encounters per week, achieving 96% patient satisfaction scores', 'Managed 200 client interactions per week, achieving 96% satisfaction scores', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('medical_junior_officer_extra_1', 'Medical', 'junior_officer', '{action_verb} medical support for {count} personnel, maintaining {metric}% medical readiness', 'Provided medical support for 500 soldiers, maintaining 97% medical readiness rate', 'Coordinated healthcare services for 500 employees, maintaining 97% health compliance rate', '{"action_verb","count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('medical_junior_officer_extra_2', 'Medical', 'junior_officer', 'Managed {count} patient encounters per {timeframe}, achieving {metric}% patient satisfaction', 'Managed 200 patient encounters per week, achieving 96% patient satisfaction scores', 'Managed 200 client interactions per week, achieving 96% satisfaction scores', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('medical_senior_officer_extra_1', 'Medical', 'senior_officer', '{action_verb} medical support for {count} personnel, maintaining {metric}% medical readiness', 'Provided medical support for 500 soldiers, maintaining 97% medical readiness rate', 'Coordinated healthcare services for 500 employees, maintaining 97% health compliance rate', '{"action_verb","count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('medical_senior_officer_extra_2', 'Medical', 'senior_officer', 'Managed {count} patient encounters per {timeframe}, achieving {metric}% patient satisfaction', 'Managed 200 patient encounters per week, achieving 96% patient satisfaction scores', 'Managed 200 client interactions per week, achieving 96% satisfaction scores', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('medical_warrant_officer_extra_1', 'Medical', 'warrant_officer', '{action_verb} medical support for {count} personnel, maintaining {metric}% medical readiness', 'Provided medical support for 500 soldiers, maintaining 97% medical readiness rate', 'Coordinated healthcare services for 500 employees, maintaining 97% health compliance rate', '{"action_verb","count","metric"}', '{}') ON CONFLICT DO NOTHING;
INSERT INTO dict_bullet_patterns (pattern_name, category, rank_tier, pattern_template, example_military, example_output, required_fields, optional_fields) VALUES ('medical_warrant_officer_extra_2', 'Medical', 'warrant_officer', 'Managed {count} patient encounters per {timeframe}, achieving {metric}% patient satisfaction', 'Managed 200 patient encounters per week, achieving 96% patient satisfaction scores', 'Managed 200 client interactions per week, achieving 96% satisfaction scores', '{"count","timeframe","metric"}', '{}') ON CONFLICT DO NOTHING;

-- dict_bullet_patterns (extra): 95 INSERT statements