-- dict_acronyms (part a)
-- 400 INSERT statements
-- Run in Supabase SQL Editor


-- BRANCH VALUES: Use lowercase abbreviations ONLY
-- army, navy, usaf, usmc, uscg, ussf, general
-- NEVER use full names like 'Coast Guard' or 'Air Force'
-- Domain context values (logistics, intelligence, cyber, etc.) are also valid
-- Run validate-branch-values.sh before pasting into Supabase

BEGIN;

-- ----- Branch: all -----
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DoD', 'Department of Defense', 'Department of Defense', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DOD', 'Department of Defense', 'Department of Defense', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CONUS', 'continental United States', 'continental United States', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OCONUS', 'overseas', 'overseas', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ORM', 'operational risk management', 'operational risk management', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CRM', 'crew resource management', 'crew resource management', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TDY', 'temporary duty assignment', 'temporary duty assignment', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TAD', 'temporary assignment', 'temporary assignment', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PCS', 'permanent relocation', 'permanent relocation', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DEROS', 'scheduled rotation date', 'scheduled rotation date', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ETS', 'end of service obligation', 'end of service obligation', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MOS', 'military occupational specialty', 'military occupational specialty', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AFSC', 'career field specialty code', 'career field specialty code', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NEC', 'specialty code', 'specialty code', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OJT', 'on-the-job training', 'on-the-job training', 'general', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PME', 'professional military education', 'professional military education', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CBT', 'computer-based training', 'computer-based training', 'general', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('GMT', 'mandatory training', 'mandatory training', 'general', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AAR', 'after-action review', 'after-action review', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SOP', 'standard operating procedure', 'standard operating procedure', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ROE', 'rules of engagement', 'rules of engagement', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OPORD', 'operations order', 'operations order', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FRAGO', 'change to operations order', 'change to operations order', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('WARNO', 'advance notice', 'advance notice', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SITREP', 'status report', 'status report', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SPOTREP', 'incident report', 'incident report', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SALUTE', 'threat report format', 'threat report format', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MEDEVAC', 'medical evacuation', 'medical evacuation', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CASEVAC', 'casualty evacuation', 'casualty evacuation', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('KIA', 'killed in action', 'killed in action', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('WIA', 'wounded in action', 'wounded in action', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MIA', 'missing in action', 'missing in action', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('POW', 'prisoner of war', 'prisoner of war', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('IED', 'improvised explosive device', 'improvised explosive device', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('UXO', 'unexploded ordnance', 'unexploded ordnance', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('EOD', 'explosive ordnance disposal', 'explosive ordnance disposal', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CBRN', 'chemical/biological/radiological/nuclear defense', 'chemical/biological/radiological/nuclear defense', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('HAZMAT', 'hazardous materials', 'hazardous materials', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PPE', 'personal protective equipment', 'personal protective equipment', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MOPP', 'protective posture level', 'protective posture level', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('IA', 'individual augmentee', 'individual augmentee', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('JTF', 'joint task force', 'joint task force', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('COCOM', 'combatant command', 'combatant command', 'general', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CENTCOM', 'Central Command', 'Central Command', 'general', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('EUCOM', 'European Command', 'European Command', 'general', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PACOM', 'Pacific Command', 'Pacific Command', 'general', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('INDOPACOM', 'Indo-Pacific Command', 'Indo-Pacific Command', 'general', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SOCOM', 'Special Operations Command', 'Special Operations Command', 'general', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TRANSCOM', 'Transportation Command', 'Transportation Command', 'general', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CYBERCOM', 'Cyber Command', 'Cyber Command', 'general', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('STRATCOM', 'Strategic Command', 'Strategic Command', 'general', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NORTHCOM', 'Northern Command', 'Northern Command', 'general', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SOUTHCOM', 'Southern Command', 'Southern Command', 'general', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AFRICOM', 'Africa Command', 'Africa Command', 'general', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AOR', 'area of responsibility', 'area of responsibility', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('COP', 'common operating picture', 'common operating picture', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TOC', 'tactical operations center', 'tactical operations center', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CP', 'command post', 'command post', 'general', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('HQ', 'headquarters', 'headquarters', 'general', 'Facility') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('IG', 'inspector general', 'inspector general', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('JAG', 'legal affairs', 'legal affairs', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SJA', 'staff judge advocate', 'staff judge advocate', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PAO', 'public affairs', 'public affairs', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OPSEC', 'operations security', 'operations security', 'general', 'Security') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PERSEC', 'personnel security', 'personnel security', 'general', 'Security') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('INFOSEC', 'information security', 'information security', 'general', 'Security') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('COMSEC', 'communications security', 'communications security', 'general', 'Security') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SSO', 'special security officer', 'special security officer', 'general', 'Security') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SCO', 'security control officer', 'security control officer', 'general', 'Security') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FSO', 'facility security officer', 'facility security officer', 'general', 'Security') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SCI', 'sensitive compartmented information', 'sensitive compartmented information', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SAP', 'special access program', 'special access program', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NOFORN', 'not releasable to foreign nationals', 'not releasable to foreign nationals', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FOUO', 'for official use only', 'for official use only', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CUI', 'controlled unclassified information', 'controlled unclassified information', 'general', 'Security') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('UCMJ', 'military justice code', 'military justice code', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NJP', 'non-judicial punishment', 'non-judicial punishment', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('LOC', 'letter of counseling', 'letter of counseling', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('LOR', 'letter of reprimand', 'letter of reprimand', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('LOA', 'letter of admonishment', 'letter of admonishment', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('GCM', 'general court-martial', 'general court-martial', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SPCM', 'special court-martial', 'special court-martial', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SCM', 'summary court-martial', 'summary court-martial', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SAPR', 'sexual assault prevention', 'sexual assault prevention', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SHARP', 'sexual harassment/assault prevention', 'sexual harassment/assault prevention', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('EO', 'equal opportunity', 'equal opportunity', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MEO', 'military equal opportunity', 'military equal opportunity', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DEOCS', 'organizational climate survey', 'organizational climate survey', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MWR', 'morale, welfare and recreation', 'morale, welfare and recreation', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('USO', 'United Service Organizations', 'United Service Organizations', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DFAS', 'finance and accounting', 'finance and accounting', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('LES', 'leave and earnings statement', 'leave and earnings statement', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('BAH', 'housing allowance', 'housing allowance', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('BAS', 'subsistence allowance', 'subsistence allowance', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('COLA', 'cost of living allowance', 'cost of living allowance', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SRB', 'selective reenlistment bonus', 'selective reenlistment bonus', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TSP', 'Thrift Savings Plan', 'Thrift Savings Plan', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SGLI', 'service member life insurance', 'service member life insurance', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TRICARE', 'military health insurance', 'military health insurance', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('VA', 'Veterans Affairs', 'Veterans Affairs', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TAP', 'transition assistance program', 'transition assistance program', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TAPS', 'transition assistance program', 'transition assistance program', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('EAOS', 'end of service obligation', 'end of service obligation', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PRD', 'planned rotation date', 'planned rotation date', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('EAS', 'end of active service', 'end of active service', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DOS', 'date of separation', 'date of separation', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ERB', 'personnel record', 'personnel record', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OMPF', 'official personnel file', 'official personnel file', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('iPERMS', 'electronic personnel records', 'electronic personnel records', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NSIPS', 'personnel management system', 'personnel management system', 'general', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MOL', 'Marine Online portal', 'Marine Online portal', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AKO', 'Army knowledge portal', 'Army knowledge portal', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('vMPF', 'virtual personnel center', 'virtual personnel center', 'general', 'Acronym') ON CONFLICT DO NOTHING;
-- ----- Branch: Navy -----
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OMMS-NG', 'maintenance tracking system', 'maintenance tracking system', 'navy', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('JCN', 'work order', 'work order', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PMS', 'preventive maintenance', 'preventive maintenance', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SKED', 'scheduling system', 'scheduling system', 'navy', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CSMP', 'maintenance backlog', 'maintenance backlog', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MRC', 'maintenance procedures', 'maintenance procedures', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TYCOM', 'command-level', 'command-level', 'navy', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('IEM', 'equipment inspection', 'equipment inspection', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AWP', 'parts shortage', 'parts shortage', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('WCS', 'Maintenance Team Lead', 'Maintenance Team Lead', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('3MA', 'Maintenance Program Manager', 'Maintenance Program Manager', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('3MC', 'Maintenance Coordinator', 'Maintenance Coordinator', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('3M', 'maintenance program', 'maintenance program', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('INSURV', 'regulatory compliance inspection', 'regulatory compliance inspection', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ATG', 'operational readiness evaluation', 'operational readiness evaluation', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DCPO', 'maintenance supervisor', 'maintenance supervisor', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FITREP', 'performance evaluation', 'performance evaluation', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NAVFIT', 'performance evaluation system', 'performance evaluation system', 'navy', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('EVAL', 'performance evaluation', 'performance evaluation', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('LPO', 'team lead', 'team lead', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('LCPO', 'senior team lead', 'senior team lead', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CMC', 'senior enlisted advisor', 'senior enlisted advisor', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('XO', 'deputy director', 'deputy director', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CO', 'director', 'director', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CHENG', 'chief engineer', 'chief engineer', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DCA', 'safety officer', 'safety officer', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OOD', 'officer of the watch', 'officer of the watch', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('EOOW', 'engineering watch officer', 'engineering watch officer', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CDO', 'command duty officer', 'command duty officer', 'navy', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('JOOD', 'junior officer of the watch', 'junior officer of the watch', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('BMOW', 'bridge watch supervisor', 'bridge watch supervisor', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CIC', 'operations center', 'operations center', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CDC', 'operations center', 'operations center', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('COMMS', 'communications', 'communications', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OPREP', 'operational report', 'operational report', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CASREP', 'equipment casualty report', 'equipment casualty report', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SORTS', 'readiness reporting', 'readiness reporting', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DRRS', 'readiness reporting', 'readiness reporting', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SPAWAR', 'naval systems command', 'naval systems command', 'navy', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NAVWAR', 'naval information warfare systems', 'naval information warfare systems', 'navy', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PEO', 'program executive office', 'program executive office', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NAVSEA', 'naval systems command', 'naval systems command', 'navy', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NAVAIR', 'naval aviation systems', 'naval aviation systems', 'navy', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NAVSUP', 'supply command', 'supply command', 'navy', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OPNAV', 'headquarters staff', 'headquarters staff', 'navy', 'Facility') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ISIC', 'immediate superior command', 'immediate superior command', 'navy', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DESRON', 'destroyer squadron', 'destroyer squadron', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CSG', 'carrier strike group', 'carrier strike group', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ESG', 'expeditionary strike group', 'expeditionary strike group', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AIRDET', 'aviation detachment', 'aviation detachment', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('UNREP', 'underway replenishment', 'underway replenishment', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('RAS', 'replenishment at sea', 'replenishment at sea', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('GQ', 'general quarters', 'general quarters', 'navy', 'Facility') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DC', 'damage control', 'damage control', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DCTT', 'damage control training team', 'damage control training team', 'navy', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TQL', 'total quality leadership', 'total quality leadership', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PQS', 'personnel qualification standards', 'personnel qualification standards', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NKO', 'online training system', 'online training system', 'navy', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NEL', 'Navy e-Learning', 'Navy e-Learning', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CANTRAC', 'training catalog', 'training catalog', 'navy', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('BCA', 'fitness standards assessment', 'fitness standards assessment', 'navy', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PRT', 'physical readiness test', 'physical readiness test', 'navy', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FEP', 'fitness enhancement program', 'fitness enhancement program', 'navy', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DAPA', 'substance abuse prevention advisor', 'substance abuse prevention advisor', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CFL', 'command fitness leader', 'command fitness leader', 'navy', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SARC', 'sexual assault response coordinator', 'sexual assault response coordinator', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CMEO', 'equal opportunity manager', 'equal opportunity manager', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ESO', 'educational services officer', 'educational services officer', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NC', 'career counselor', 'career counselor', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CCC', 'command career counselor', 'command career counselor', 'navy', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CACO', 'casualty assistance officer', 'casualty assistance officer', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DIVO', 'division officer', 'division officer', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DH', 'department head', 'department head', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SUPPO', 'supply officer', 'supply officer', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NAV', 'navigator', 'navigator', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OPS', 'operations', 'operations', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('WEPS', 'weapons officer', 'weapons officer', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('COMMO', 'communications officer', 'communications officer', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AOPS', 'assistant operations officer', 'assistant operations officer', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('EMO', 'electronics material officer', 'electronics material officer', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MPA', 'main propulsion assistant', 'main propulsion assistant', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AUXO', 'auxiliaries officer', 'auxiliaries officer', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ADMIN', 'administration', 'administration', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FLC', 'fleet logistics center', 'fleet logistics center', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FISC', 'fleet industrial supply center', 'fleet industrial supply center', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NSA', 'naval support activity', 'naval support activity', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NAS', 'naval air station', 'naval air station', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NAVSTA', 'naval station', 'naval station', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CNSP', 'Commander Naval Surface Forces Pacific', 'Commander Naval Surface Forces Pacific', 'navy', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CNAL', 'Commander Naval Air Forces Atlantic', 'Commander Naval Air Forces Atlantic', 'navy', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SURFLANT', 'surface forces Atlantic', 'surface forces Atlantic', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SURFPAC', 'surface forces Pacific', 'surface forces Pacific', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AIRLANT', 'air forces Atlantic', 'air forces Atlantic', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AIRPAC', 'air forces Pacific', 'air forces Pacific', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SUBLANT', 'submarine forces Atlantic', 'submarine forces Atlantic', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SUBPAC', 'submarine forces Pacific', 'submarine forces Pacific', 'navy', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CTN', 'cryptologic technician (networks)', 'cryptologic technician (networks)', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('IT', 'information technology', 'information technology', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ITS', 'information technology submariner', 'information technology submariner', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ET', 'electronics technician', 'electronics technician', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FC', 'fire controlman', 'fire controlman', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OS', 'operations specialist', 'operations specialist', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('QM', 'quartermaster', 'quartermaster', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('BM', 'boatswain''s mate', 'boatswain''s mate', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('HM', 'hospital corpsman', 'hospital corpsman', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MA', 'master-at-arms', 'master-at-arms', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('LS', 'logistics specialist', 'logistics specialist', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PS', 'personnel specialist', 'personnel specialist', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('YN', 'yeoman', 'yeoman', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SK', 'storekeeper', 'storekeeper', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('HT', 'hull maintenance technician', 'hull maintenance technician', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MM', 'machinist''s mate', 'machinist''s mate', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('EN', 'engineman', 'engineman', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('GSM', 'gas turbine systems mechanic', 'gas turbine systems mechanic', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('GSE', 'gas turbine systems electrician', 'gas turbine systems electrician', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('EM', 'electrician''s mate', 'electrician''s mate', 'navy', 'Rating') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('IC', 'interior communications electrician', 'interior communications electrician', 'navy', 'Rating') ON CONFLICT DO NOTHING;
-- ----- Branch: Army -----
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NCOER', 'performance evaluation', 'performance evaluation', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OER', 'officer performance evaluation', 'officer performance evaluation', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NCOIC', 'non-commissioned officer in charge', 'non-commissioned officer in charge', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OIC', 'officer in charge', 'officer in charge', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NCO', 'non-commissioned officer', 'non-commissioned officer', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SNCO', 'senior non-commissioned officer', 'senior non-commissioned officer', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CSM', 'command sergeant major', 'command sergeant major', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SGM', 'sergeant major', 'sergeant major', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SFC', 'sergeant first class', 'sergeant first class', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SSG', 'staff sergeant', 'staff sergeant', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SGT', 'sergeant', 'sergeant', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CPL', 'corporal', 'corporal', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SPC', 'specialist', 'specialist', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PFC', 'private first class', 'private first class', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PV2', 'private', 'private', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PVT', 'private', 'private', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('BCT', 'brigade combat team', 'brigade combat team', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('BDE', 'brigade', 'brigade', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('BN', 'battalion', 'battalion', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PLT', 'platoon', 'platoon', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SQD', 'squad', 'squad', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TM', 'team', 'team', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('HHC', 'headquarters company', 'headquarters company', 'army', 'Facility') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FSC', 'forward support company', 'forward support company', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('BSB', 'brigade support battalion', 'brigade support battalion', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DIVARTY', 'division artillery', 'division artillery', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CAB', 'combat aviation brigade', 'combat aviation brigade', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SBCT', 'Stryker brigade combat team', 'Stryker brigade combat team', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ABCT', 'armored brigade combat team', 'armored brigade combat team', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('IBCT', 'infantry brigade combat team', 'infantry brigade combat team', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FORSCOM', 'Forces Command', 'Forces Command', 'army', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TRADOC', 'Training and Doctrine Command', 'Training and Doctrine Command', 'army', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AMC', 'Army Materiel Command', 'Army Materiel Command', 'army', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('INSCOM', 'Intelligence and Security Command', 'Intelligence and Security Command', 'army', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('USAREC', 'Army Recruiting Command', 'Army Recruiting Command', 'army', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('IMCOM', 'Installation Management Command', 'Installation Management Command', 'army', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MEDCOM', 'Medical Command', 'Medical Command', 'army', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('USACE', 'Army Corps of Engineers', 'Army Corps of Engineers', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PBO', 'property book officer', 'property book officer', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('S1', 'human resources/personnel', 'human resources/personnel', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('S2', 'intelligence/security', 'intelligence/security', 'army', 'Security') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('S3', 'operations/training', 'operations/training', 'army', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('S4', 'logistics/supply', 'logistics/supply', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('S6', 'communications/IT', 'communications/IT', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('G1', 'division/corps personnel', 'division/corps personnel', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('G2', 'division/corps intelligence', 'division/corps intelligence', 'army', 'Security') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('G3', 'division/corps operations', 'division/corps operations', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('G4', 'division/corps logistics', 'division/corps logistics', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('G6', 'division/corps communications', 'division/corps communications', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('J1', 'joint personnel', 'joint personnel', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('J2', 'joint intelligence', 'joint intelligence', 'army', 'Security') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('J3', 'joint operations', 'joint operations', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('J4', 'joint logistics', 'joint logistics', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('J6', 'joint communications', 'joint communications', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PSG', 'platoon sergeant', 'platoon sergeant', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ISG', 'first sergeant', 'first sergeant', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('1SG', 'first sergeant', 'first sergeant', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SL', 'squad leader', 'squad leader', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TL', 'team leader', 'team leader', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('APFT', 'physical fitness test', 'physical fitness test', 'army', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ACFT', 'combat fitness test', 'combat fitness test', 'army', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DA', 'Department of the Army', 'Department of the Army', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AR', 'Army regulation', 'Army regulation', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FM', 'field manual', 'field manual', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OPFOR', 'opposing force', 'opposing force', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('BLUFOR', 'friendly force', 'friendly force', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NTC', 'National Training Center', 'National Training Center', 'army', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('JRTC', 'Joint Readiness Training Center', 'Joint Readiness Training Center', 'army', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CTC', 'combat training center', 'combat training center', 'army', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FTX', 'field training exercise', 'field training exercise', 'army', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('STX', 'situational training exercise', 'situational training exercise', 'army', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('LFX', 'live fire exercise', 'live fire exercise', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TADSS', 'training aids and devices', 'training aids and devices', 'army', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DTMS', 'digital training management system', 'digital training management system', 'army', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('USR', 'unit status report', 'unit status report', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MTOE', 'personnel and equipment authorization', 'personnel and equipment authorization', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TDA', 'organizational structure document', 'organizational structure document', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('UMR', 'unit manning report', 'unit manning report', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MEDPROS', 'medical readiness system', 'medical readiness system', 'army', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DPAS', 'property accountability system', 'property accountability system', 'army', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PBUSE', 'property management system', 'property management system', 'army', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('eMILPO', 'personnel management system', 'personnel management system', 'army', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ATTRS', 'training requirements system', 'training requirements system', 'army', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DTS', 'travel management system', 'travel management system', 'army', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('GFEBS', 'financial management system', 'financial management system', 'army', 'System') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PMCS', 'preventive maintenance checks', 'preventive maintenance checks', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TI', 'technical inspection', 'technical inspection', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('QA', 'quality assurance', 'quality assurance', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('QC', 'quality control', 'quality control', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('COMMEX', 'communications exercise', 'communications exercise', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('LOGPAC', 'logistics package', 'logistics package', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MSR', 'main supply route', 'main supply route', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ASR', 'alternate supply route', 'alternate supply route', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FOB', 'forward operating base', 'forward operating base', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PB', 'patrol base', 'patrol base', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('JSS', 'joint security station', 'joint security station', 'army', 'Security') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ECP', 'entry control point', 'entry control point', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TCP', 'traffic control point', 'traffic control point', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CONOP', 'concept of operations', 'concept of operations', 'army', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('EXORD', 'execute order', 'execute order', 'army', 'Acronym') ON CONFLICT DO NOTHING;
-- ----- Branch: Marines -----
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('USMC', 'United States Marine Corps', 'United States Marine Corps', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MARDIV', 'Marine Division', 'Marine Division', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MAW', 'Marine Aircraft Wing', 'Marine Aircraft Wing', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MLG', 'Marine Logistics Group', 'Marine Logistics Group', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MEF', 'Marine Expeditionary Force', 'Marine Expeditionary Force', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MEB', 'Marine Expeditionary Brigade', 'Marine Expeditionary Brigade', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MEU', 'Marine Expeditionary Unit', 'Marine Expeditionary Unit', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MAGTF', 'Marine Air-Ground Task Force', 'Marine Air-Ground Task Force', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('GCE', 'ground combat element', 'ground combat element', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ACE', 'aviation combat element', 'aviation combat element', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('LCE', 'logistics combat element', 'logistics combat element', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CE', 'command element', 'command element', 'usmc', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('HQMC', 'Headquarters Marine Corps', 'Headquarters Marine Corps', 'usmc', 'Facility') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SMMC', 'Sergeant Major of the Marine Corps', 'Sergeant Major of the Marine Corps', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MARFORCOM', 'Marine Forces Command', 'Marine Forces Command', 'usmc', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MARFORPAC', 'Marine Forces Pacific', 'Marine Forces Pacific', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MCRD', 'Marine Corps Recruit Depot', 'Marine Corps Recruit Depot', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TBS', 'The Basic School', 'The Basic School', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('IOC', 'Infantry Officer Course', 'Infantry Officer Course', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SOI', 'School of Infantry', 'School of Infantry', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MCB', 'Marine Corps Base', 'Marine Corps Base', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MCAS', 'Marine Corps Air Station', 'Marine Corps Air Station', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MCLB', 'Marine Corps Logistics Base', 'Marine Corps Logistics Base', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MCSC', 'Marine Corps Systems Command', 'Marine Corps Systems Command', 'usmc', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MCWL', 'Marine Corps Warfighting Lab', 'Marine Corps Warfighting Lab', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('TECOM', 'Training and Education Command', 'Training and Education Command', 'usmc', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MCCDC', 'Combat Development Command', 'Combat Development Command', 'usmc', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MARCENT', 'Marine Forces Central Command', 'Marine Forces Central Command', 'usmc', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SNCOIC', 'senior NCO in charge', 'senior NCO in charge', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MECEP', 'enlisted commissioning program', 'enlisted commissioning program', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MARADMIN', 'Marine administrative message', 'Marine administrative message', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ALMAR', 'all Marines message', 'all Marines message', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CFT', 'combat fitness test', 'combat fitness test', 'usmc', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PFT', 'physical fitness test', 'physical fitness test', 'usmc', 'Training') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MCMAP', 'martial arts program', 'martial arts program', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PMO', 'provost marshal office', 'provost marshal office', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SMP', 'squadron maintenance program', 'squadron maintenance program', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MALS', 'Marine Aviation Logistics Squadron', 'Marine Aviation Logistics Squadron', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('VMFA', 'Marine Fighter Attack Squadron', 'Marine Fighter Attack Squadron', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('VMM', 'Marine Medium Tiltrotor Squadron', 'Marine Medium Tiltrotor Squadron', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('HMH', 'Marine Heavy Helicopter Squadron', 'Marine Heavy Helicopter Squadron', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('HMLA', 'Marine Light Attack Helicopter Squadron', 'Marine Light Attack Helicopter Squadron', 'usmc', 'Acronym') ON CONFLICT DO NOTHING;
-- ----- Branch: Air Force -----
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('USAF', 'United States Air Force', 'United States Air Force', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('EPR', 'performance evaluation', 'performance evaluation', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OPR', 'officer performance report', 'officer performance report', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AF', 'usaf', 'usaf', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AFI', 'Air Force instruction', 'Air Force instruction', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AFMAN', 'Air Force manual', 'Air Force manual', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AFPD', 'Air Force policy directive', 'Air Force policy directive', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ACC', 'Air Combat Command', 'Air Combat Command', 'usaf', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AETC', 'Air Education and Training Command', 'Air Education and Training Command', 'usaf', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AFGSC', 'Air Force Global Strike Command', 'Air Force Global Strike Command', 'usaf', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AFSPC', 'Air Force Space Command', 'Air Force Space Command', 'usaf', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AFSOC', 'Air Force Special Operations Command', 'Air Force Special Operations Command', 'usaf', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('PACAF', 'Pacific Air Forces', 'Pacific Air Forces', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('USAFE', 'US Air Forces in Europe', 'US Air Forces in Europe', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('ANG', 'Air National Guard', 'Air National Guard', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('AFRC', 'Air Force Reserve Command', 'Air Force Reserve Command', 'usaf', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MAJCOM', 'major command', 'major command', 'usaf', 'Organization') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('NAF', 'numbered air force', 'numbered air force', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('OG', 'operations group', 'operations group', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MXG', 'maintenance group', 'maintenance group', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MSG', 'mission support group', 'mission support group', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MDG', 'medical group', 'medical group', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('SQ', 'squadron', 'squadron', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('FLT', 'flight', 'flight', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CC', 'commander', 'commander', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('CD', 'deputy commander', 'deputy commander', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('DO', 'director of operations', 'director of operations', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_acronyms (acronym, full_term, civilian_explanation, branch, category) VALUES ('MX', 'maintenance', 'maintenance', 'usaf', 'Acronym') ON CONFLICT DO NOTHING;

COMMIT;
