-- dict_military_jargon
-- 477 INSERT statements
-- Run in Supabase SQL Editor


-- BRANCH VALUES: Use lowercase abbreviations ONLY
-- army, navy, usaf, usmc, uscg, ussf, general
-- NEVER use full names like 'Coast Guard' or 'Air Force'
-- Domain context values (logistics, intelligence, cyber, etc.) are also valid
-- Run validate-branch-values.sh before pasting into Supabase

BEGIN;

-- Acronyms (186 entries)
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('AAR', 'after-action review / post-project analysis', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ACDU', 'active duty', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ADCON', 'administrative control', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('AFB', 'Air Force Base / facility', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('AFSC', 'Air Force Specialty Code / job classification', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('AIT', 'Advanced Individual Training / technical certification program', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('AO', 'area of operations / assigned region', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('AOR', 'area of responsibility / managed territory', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('APFT', 'Army Physical Fitness Test / physical readiness assessment', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('AT', 'annual training', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('AWOL', 'absent without leave / unauthorized absence', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('BAH', 'Basic Allowance for Housing / housing stipend', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('BAS', 'Basic Allowance for Subsistence / meal allowance', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('BCT', 'Basic Combat Training / initial training program', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('BN', 'battalion / large organizational unit', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('BRAC', 'Base Realignment and Closure', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CAC', 'Common Access Card / security credential', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CASREP', 'casualty report / equipment status report', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CDC', 'Career Development Course / professional development program', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CINC', 'Commander in Chief', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CMR', 'Consolidated Memorandum Receipt / inventory document', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CO', 'Commanding Officer / director / executive', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('COB', 'close of business', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CONUS', 'continental United States / domestic', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('COR', 'Contracting Officer Representative', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('COTS', 'commercial off-the-shelf', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CPO', 'Chief Petty Officer', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CSS', 'combat service support / operational support', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('DA', 'Department of the Army', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('DANTES', 'Defense Activity for Non-Traditional Education Support', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('DCAS', 'Defense Contract Audit Services', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('DD214', 'separation document / discharge paperwork', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('DFAS', 'Defense Finance and Accounting Service', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('DLA', 'Defense Logistics Agency', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('DOD', 'Department of Defense', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('DRMO', 'Defense Reutilization and Marketing Office / surplus disposal', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('DTS', 'Defense Travel System / travel management system', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('DUSTWUN', 'duty status whereabouts unknown', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('EAS', 'End of Active Service / contract completion date', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('EDIPI', 'Electronic Data Interchange Personal Identifier', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('EEO', 'Equal Employment Opportunity', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('EFMP', 'Exceptional Family Member Program', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('EOD', 'Explosive Ordnance Disposal / bomb disposal', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('EOOW', 'Engineering Officer of the Watch / shift supervisor', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ETS', 'Expiration Term of Service / end of contract', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('EVAL', 'performance evaluation / annual review', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('FAP', 'Family Advocacy Program', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('FITREP', 'fitness report / officer performance review', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('FMC', 'fully mission capable / operational ready', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('FORSCOM', 'Forces Command', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('FRG', 'Family Readiness Group', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('FSA', 'Family Separation Allowance', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('FTX', 'field training exercise / hands-on training event', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('GCSS', 'Global Combat Support System', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('GMT', 'General Military Training / annual training requirements', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('GSA', 'General Services Administration', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('HHG', 'household goods / personal property', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('HM', 'Hospital Corpsman / medical technician', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('HQ', 'headquarters / corporate office', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('HQDA', 'Headquarters Department of the Army', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('IA', 'Individual Augmentee / temporary assignment', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('IED', 'improvised explosive device', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('IG', 'Inspector General / compliance auditor', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('INSURV', 'Board of Inspection and Survey', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('IPR', 'in-progress review / status update meeting', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('IRR', 'Individual Ready Reserve', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ISIC', 'Immediate Superior in Command', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('JAG', 'Judge Advocate General / legal department', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('JCS', 'Joint Chiefs of Staff', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('JFTR', 'Joint Federal Travel Regulation', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('JPAS', 'Joint Personnel Adjudication System', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('JQR', 'Job Qualification Requirements', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('JTR', 'Joint Travel Regulations', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('KIA', 'killed in action', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('LES', 'Leave and Earnings Statement / pay stub', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('LOD', 'line of duty', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('LPO', 'Leading Petty Officer / team supervisor', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('LCPO', 'Lead Chief Petty Officer / department supervisor', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('LZ', 'landing zone', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MARADMIN', 'Marine Administrative Message', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MCO', 'Marine Corps Order / policy directive', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MCPON', 'Master Chief Petty Officer of the Navy', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MIA', 'missing in action', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MILCON', 'military construction', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MILPER', 'military personnel', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MOC', 'Military Occupational Code', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MOS', 'Military Occupational Specialty / job classification', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MOU', 'Memorandum of Understanding / formal agreement', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MRE', 'Meal Ready to Eat / field rations', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MWR', 'Morale, Welfare and Recreation / employee services', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NAF', 'Non-Appropriated Fund', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NATO', 'North Atlantic Treaty Organization', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NAVADMIN', 'Navy Administrative Message / policy announcement', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NEC', 'Navy Enlisted Classification / specialty code', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NCO', 'Non-Commissioned Officer / supervisor', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NCOER', 'NCO Evaluation Report / performance review', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NCOIC', 'Non-Commissioned Officer in Charge / shift supervisor', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NJP', 'Non-Judicial Punishment / disciplinary action', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NKO', 'Navy Knowledge Online / e-learning platform', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NLT', 'no later than / deadline', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NMCI', 'Navy Marine Corps Intranet', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NMCRS', 'Navy-Marine Corps Relief Society', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NSN', 'National Stock Number / part number', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('OCS', 'Officer Candidate School', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('OCONUS', 'outside continental United States / overseas', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('OER', 'Officer Evaluation Report / performance review', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('OIC', 'Officer in Charge / department head', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('OJT', 'on-the-job training', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('OOD', 'Officer of the Deck / watch supervisor', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('OPNAV', 'Office of the Chief of Naval Operations', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('OPORD', 'operations order / project plan', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('OPSEC', 'operational security / information security', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ORM', 'Operational Risk Management / risk assessment', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('OSI', 'Office of Special Investigations', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('OTS', 'Officer Training School', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PAO', 'Public Affairs Officer / communications manager', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PCS', 'Permanent Change of Station / relocation', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PFA', 'Physical Fitness Assessment', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PFT', 'Physical Fitness Test', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PME', 'Professional Military Education / professional development', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PMO', 'Provost Marshal Office / military police HQ', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('POA&M', 'Plan of Action and Milestones / project timeline', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('POC', 'point of contact', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('POD', 'Plan of the Day / daily schedule', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('POV', 'privately owned vehicle', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('POW', 'prisoner of war', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PPE', 'personal protective equipment', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PQS', 'Personnel Qualification Standards / certification requirements', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PT', 'physical training / fitness program', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PTA', 'practical training assessment', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PTAD', 'permissive temporary additional duty', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('QA', 'Quality Assurance', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('QC', 'Quality Control', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('QUAL', 'qualification / certification', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('RDC', 'Recruit Division Commander / drill instructor', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('RIMPAC', 'Rim of the Pacific Exercise', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ROE', 'Rules of Engagement / operational guidelines', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ROM', 'restriction of movement', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ROTC', 'Reserve Officers'' Training Corps', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('RPO', 'Recruit Petty Officer', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('S1', 'Personnel/Admin section / HR department', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('S2', 'Intelligence section / analysis department', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('S3', 'Operations section / operations department', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('S4', 'Logistics section / supply chain department', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('S6', 'Communications section / IT department', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SAPR', 'Sexual Assault Prevention and Response', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SARC', 'Sexual Assault Response Coordinator', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SCI', 'Sensitive Compartmented Information', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SCIF', 'Sensitive Compartmented Information Facility / secure facility', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SDO', 'Staff Duty Officer / on-call manager', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SEAL', 'Sea, Air, and Land / special operations', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SECDEF', 'Secretary of Defense', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SECNAV', 'Secretary of the Navy', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SELRES', 'Selected Reserve', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SF', 'Standard Form', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SIQ', 'Sick in Quarters / medical leave', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SITREP', 'situation report / status update', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SJA', 'Staff Judge Advocate / legal counsel', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SL', 'skill level', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SM', 'service member / employee', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SME', 'subject matter expert', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SNCO', 'Staff Non-Commissioned Officer / senior supervisor', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SOP', 'Standard Operating Procedure', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SRB', 'Selective Reenlistment Bonus', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('TAD', 'Temporary Additional Duty / temporary assignment', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('TBS', 'The Basic School / officer training', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('TDY', 'Temporary Duty / business travel', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('TIG', 'Time in Grade / time at current level', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('TIS', 'Time in Service / tenure', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('TMO', 'Traffic Management Office / shipping coordinator', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('TOC', 'Tactical Operations Center / operations center', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('TRICARE', 'military healthcare system', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('TSP', 'Thrift Savings Plan / retirement plan', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('UA', 'unauthorized absence / no-call no-show', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('UAV', 'unmanned aerial vehicle / drone', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('UCMJ', 'Uniform Code of Military Justice / military law', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('UIC', 'Unit Identification Code', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('UNODIR', 'unless otherwise directed', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('USERRA', 'Uniformed Services Employment and Reemployment Rights Act', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('VA', 'Veterans Affairs / veterans services', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('VHA', 'Variable Housing Allowance', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('WIA', 'wounded in action', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('WO', 'Warrant Officer / technical expert', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('WTI', 'Weapons and Tactics Instructor', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('XO', 'Executive Officer / deputy director / second-in-command', 'general', 'Acronym') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('YN', 'Yeoman / administrative specialist', 'general', 'Acronym') ON CONFLICT DO NOTHING;
-- Military Terms (194 entries)
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('active duty', 'full-time employment', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('advancement', 'promotion', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('afloat', 'shipboard / maritime operations', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ashore', 'land-based / office environment', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('at sea', 'deployed / offshore operations', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('barracks', 'company housing / dormitory', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('battle rhythm', 'operational cadence / recurring schedule', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('billet', 'position / role / job', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('blue jacket', 'junior enlisted / entry-level employee', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('boots on ground', 'on-site personnel / field staff', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('bridging', 'cross-training / transitional training', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('broadening assignment', 'rotational assignment / developmental role', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('cadre', 'training staff / leadership team', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('chain of command', 'organizational hierarchy / reporting structure', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('chit', 'request form / approval document', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('chow', 'meals / cafeteria', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('collateral duty', 'additional responsibility / secondary assignment', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('colors', 'flag ceremony / opening/closing procedures', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('command', 'organization / business unit / department', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('command climate', 'organizational culture / work environment', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('command deck', 'executive level / senior leadership', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('commissary', 'grocery store / employee store', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('compartmentalized', 'need-to-know basis / restricted access', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('competency', 'skill / qualification', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('component', 'division / branch / department', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('contingency', 'emergency response / backup plan', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('cross-deck', 'inter-departmental transfer / rotation', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('cross-rate', 'career change / job reclassification', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('deck plate', 'frontline / shop floor / ground level', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('dependents', 'family members', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('deploy', 'travel for work / field assignment', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('deployment', 'extended business travel / overseas assignment', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('detail', 'temporary assignment / special project', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('detailer', 'career counselor / HR placement specialist', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('direct report', 'subordinate / team member', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('division', 'department / team / work group', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('division officer', 'department manager', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('dog watch', 'split shift / evening shift', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('downrange', 'in the field / at project site', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('duty', 'shift / on-call responsibility', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('duty station', 'work location / assigned office', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('echelon', 'organizational level / tier', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('effective date', 'start date', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('embarked', 'deployed / traveling for work', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('end strength', 'headcount / staffing level', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('enlisted', 'non-management / technical staff', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('eval', 'performance review / annual assessment', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('evolution', 'operation / project / task', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('exchange', 'retail store / company store', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('expeditionary', 'mobile / rapid deployment capable', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('field grade', 'senior management', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('fireteam', 'small team / work group of 4', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('fitness report', 'performance evaluation / review', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('flag officer', 'executive / C-suite', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('fleet', 'operational units / field operations', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('force protection', 'facility security / workplace safety', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('formation', 'team meeting / all-hands assembly', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('forward deployed', 'on-site at client location / field office', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('fraternization', 'inappropriate workplace relationship', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('galley', 'cafeteria / break room', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('garrison', 'permanent facility / home office', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('general quarters', 'emergency response / all-hands situation', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('gouge', 'study guide / insider information', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ground truth', 'verified information / confirmed data', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('head', 'restroom', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('headquarters', 'corporate office / main office', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('high speed', 'high performer / top talent', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('homeport', 'home office / primary work location', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('hump', 'march / endurance exercise', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('in port', 'at home office / not traveling', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('in the fleet', 'in field operations / working', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('indoc', 'orientation / onboarding', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('inspection', 'audit / compliance review', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('inspector general', 'internal auditor / compliance officer', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('inter-service', 'cross-functional / inter-departmental', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('joint', 'multi-organizational / cross-functional', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('joint duty', 'inter-agency assignment', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('junior enlisted', 'entry-level staff', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('khaki', 'supervisor / management', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('kit', 'equipment / tools / supplies', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('knock it off', 'stop immediately / cease activity', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ladder', 'stairs / career progression path', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('latrine', 'restroom', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('leave', 'paid time off / vacation', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('liberty', 'time off / personal time', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('lifer', 'career employee / long-term staff', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('line', 'operational / revenue-generating', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('log', 'record / documentation', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('logistics', 'supply chain / operations support', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('maintenance', 'equipment upkeep / preventive care', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('manifest', 'roster / inventory list', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('manning', 'staffing / headcount', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('material condition', 'equipment status / asset readiness', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('medevac', 'medical evacuation / emergency transport', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('mess', 'dining facility / cafeteria', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('mid-watch', 'overnight shift / graveyard shift', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('military bearing', 'professional demeanor / composure', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('mission', 'objective / goal / project', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('mission critical', 'essential / high priority', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('mission essential', 'critical function / required capability', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('mission ready', 'prepared / operational / qualified', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('muster', 'roll call / attendance check / team meeting', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('naval message', 'official communication / formal memo', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('non-rate', 'entry-level / undesignated', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('officer', 'manager / executive', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('on station', 'at assigned location / on post', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('operational', 'active / functioning / deployed', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('operational tempo', 'work pace / activity level', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ops', 'operations', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('order', 'directive / instruction / policy', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('orders', 'assignment notification / transfer paperwork', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('overseas', 'international / foreign location', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('passdown', 'shift handover / status briefing', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('patrol', 'monitoring / surveillance / rounds', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('pay grade', 'compensation level / salary band', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('peacetime', 'non-deployed / normal operations', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('personnel', 'staff / employees / HR', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('petty officer', 'supervisor / team lead', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('pier', 'dock / facility entrance', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('plan of the day', 'daily schedule / agenda', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('platoon', 'team of 30-50 / large work group', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('port', 'left side / destination', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('port call', 'scheduled stop / client visit', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('post', 'position / station / assignment', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('pre-deployment', 'pre-project / preparation phase', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('primary duties', 'core responsibilities', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('professional development', 'training / career growth', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('proficiency', 'skill level / competency', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('promotion', 'advancement / career progression', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('qualification', 'certification / credential', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('quarters', 'housing / living space', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('rack', 'bed / bunk', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('rating', 'job specialty / technical field', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('readiness', 'preparedness / operational capability', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('rear detachment', 'home office support / HQ staff', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('recall', 'emergency callback / urgent summons', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('reenlistment', 'contract renewal / retention', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('regiment', 'large organizational unit', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('relief', 'replacement / successor', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('relieved', 'removed from position / terminated', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('report', 'arrive / check in / start', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('reserve', 'part-time / on-call', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('restriction', 'limited privileges / probation', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('retention', 'employee retention / reenlistment', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('reveille', 'wake up call / start of day', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('rifle range', 'training facility / shooting range', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('rotation', 'assignment cycle / tour schedule', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('sailor', 'Navy employee / naval staff', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('scuttlebutt', 'rumor / informal information / water cooler talk', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('sea duty', 'deployable assignment / field position', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('secure', 'finish / complete / lock up', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('seniority', 'time in position / tenure', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('separation', 'termination / end of employment', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('service record', 'personnel file / employee record', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ship', 'vessel / facility / organization', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('shipmate', 'colleague / coworker', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('shore duty', 'office-based assignment / non-deployable role', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('short timer', 'employee near end of contract', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('sick bay', 'medical clinic / health services', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('sick call', 'medical appointment', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('skipper', 'commanding officer / CEO / president', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('smoking lamp', 'break time / authorized break', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('sortie', 'mission / operation / project execution', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('space', 'room / area / workspace', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('squadron', 'unit of 12-24 aircraft / organizational unit', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('staff', 'support personnel / administrative team', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('stand down', 'pause operations / rest period', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('standing watch', 'on-call duty / shift coverage', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('starboard', 'right side', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('station', 'assigned location / work position', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('strike', 'rate selection / career choice', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('subordinate', 'direct report / team member', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('superior', 'supervisor / manager', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('taps', 'end of day / lights out', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('task force', 'project team / special initiative group', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('theater', 'region / operational area', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('tour', 'assignment period / rotation', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('tour of duty', 'assignment length / contract period', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('training command', 'learning & development / training department', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('transfer', 'relocation / reassignment', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('troop', 'soldier / staff member', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('underway', 'in progress / actively operating', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('uniform', 'dress code / professional attire', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('unit', 'team / department / organizational element', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('vessel', 'ship / facility', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('veteran', 'former military employee', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('warfare', 'operational specialty', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('warrant officer', 'technical expert / senior specialist', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('watch', 'shift / duty period', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('watch bill', 'shift schedule / duty roster', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('watchstander', 'shift worker / on-call personnel', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('weapons qual', 'certification / proficiency test', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('workup', 'preparation / training cycle', 'general', 'Term') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('yeoman', 'administrative assistant / office manager', 'general', 'Term') ON CONFLICT DO NOTHING;
-- Navy Ranks (15 entries)
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SR (Seaman Recruit)', 'Entry-Level Staff', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SA (Seaman Apprentice)', 'Junior Staff Member', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SN (Seaman)', 'Staff Member', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PO3 (Petty Officer Third Class)', 'Team Member / Technician', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PO2 (Petty Officer Second Class)', 'Senior Technician / Team Lead', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PO1 (Petty Officer First Class)', 'Supervisor / Senior Team Lead', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CPO (Chief Petty Officer)', 'Department Supervisor / Manager', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SCPO (Senior Chief Petty Officer)', 'Senior Manager / Operations Manager', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MCPO (Master Chief Petty Officer)', 'Director / Senior Director', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('ENS (Ensign)', 'Junior Manager / Associate', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('LTJG (Lieutenant Junior Grade)', 'Manager / Project Lead', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('LT (Lieutenant)', 'Senior Manager / Department Head', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('LCDR (Lieutenant Commander)', 'Director / Senior Department Head', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CDR (Commander)', 'Senior Director / Division Head', 'navy', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CAPT (Captain)', 'Executive Director / VP', 'navy', 'Rank') ON CONFLICT DO NOTHING;
-- Army Ranks (15 entries)
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PVT (Private)', 'Entry-Level Staff', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PV2 (Private Second Class)', 'Junior Staff Member', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PFC (Private First Class)', 'Staff Member', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CPL (Corporal)', 'Team Leader', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SGT (Sergeant)', 'Team Lead / Supervisor', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SSG (Staff Sergeant)', 'Senior Supervisor', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SFC (Sergeant First Class)', 'Manager / Operations Supervisor', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('1SG (First Sergeant)', 'Operations Manager', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CSM (Command Sergeant Major)', 'Senior Director', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('2LT (Second Lieutenant)', 'Junior Manager', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('1LT (First Lieutenant)', 'Manager', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CPT (Captain)', 'Senior Manager', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MAJ (Major)', 'Director', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('LTC (Lieutenant Colonel)', 'Senior Director', 'army', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('COL (Colonel)', 'Executive Director / VP', 'army', 'Rank') ON CONFLICT DO NOTHING;
-- Air Force Ranks (15 entries)
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('AB (Airman Basic)', 'Entry-Level Staff', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('Amn (Airman)', 'Junior Staff Member', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('A1C (Airman First Class)', 'Staff Member', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SrA (Senior Airman)', 'Technician / Specialist', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SSgt (Staff Sergeant)', 'Team Lead / Supervisor', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('TSgt (Technical Sergeant)', 'Senior Supervisor', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MSgt (Master Sergeant)', 'Manager', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SMSgt (Senior Master Sergeant)', 'Senior Manager', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CMSgt (Chief Master Sergeant)', 'Director', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('2d Lt (Second Lieutenant)', 'Junior Manager', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('1st Lt (First Lieutenant)', 'Manager', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('Capt (Captain)', 'Senior Manager', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('Maj (Major)', 'Director', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('Lt Col (Lieutenant Colonel)', 'Senior Director', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('Col (Colonel)', 'Executive Director / VP', 'usaf', 'Rank') ON CONFLICT DO NOTHING;
-- Marines Ranks (15 entries)
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('Pvt (Private)', 'Entry-Level Staff', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PFC (Private First Class)', 'Junior Staff Member', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('LCpl (Lance Corporal)', 'Staff Member', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('Cpl (Corporal)', 'Team Leader', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('Sgt (Sergeant)', 'Team Lead / Supervisor', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SSgt (Staff Sergeant)', 'Senior Supervisor', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('GySgt (Gunnery Sergeant)', 'Manager', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('1stSgt (First Sergeant)', 'Operations Manager', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SgtMaj (Sergeant Major)', 'Senior Director', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('2ndLt (Second Lieutenant)', 'Junior Manager', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('1stLt (First Lieutenant)', 'Manager', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('Capt (Captain)', 'Senior Manager', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('Maj (Major)', 'Director', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('LtCol (Lieutenant Colonel)', 'Senior Director', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('Col (Colonel)', 'Executive Director / VP', 'usmc', 'Rank') ON CONFLICT DO NOTHING;
-- Coast Guard Ranks (9 entries)
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SR (Seaman Recruit)', 'Entry-Level Staff', 'uscg', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SA (Seaman Apprentice)', 'Junior Staff Member', 'uscg', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SN (Seaman)', 'Staff Member', 'uscg', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PO3 (Petty Officer Third Class)', 'Technician', 'uscg', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PO2 (Petty Officer Second Class)', 'Senior Technician / Team Lead', 'uscg', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('PO1 (Petty Officer First Class)', 'Supervisor', 'uscg', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CPO (Chief Petty Officer)', 'Manager', 'uscg', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SCPO (Senior Chief Petty Officer)', 'Senior Manager', 'uscg', 'Rank') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('MCPO (Master Chief Petty Officer)', 'Director', 'uscg', 'Rank') ON CONFLICT DO NOTHING;
-- Equipment Mappings (15 entries)
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('CBRN equipment', 'hazardous materials handling equipment', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('COMSEC', 'encrypted communications / secure communications', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('crypto', 'encryption / security systems', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('damage control equipment', 'emergency response equipment / fire suppression systems', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('EW systems', 'electronic warfare / signals systems', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('field radio', 'portable communications equipment', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('FLIR', 'thermal imaging / infrared camera', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('GPS equipment', 'navigation systems / location tracking', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('HF/UHF/VHF radio', 'radio communications systems', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('IFF systems', 'identification systems', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('NVG', 'night vision equipment / low-light optics', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('RADAR', 'radar systems / detection equipment', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SATCOM', 'satellite communications', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('SONAR', 'underwater detection systems / acoustic sensors', 'general', 'Equipment') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('tactical vehicles', 'fleet vehicles / field vehicles', 'general', 'Equipment') ON CONFLICT DO NOTHING;
-- Unit Types (13 entries)
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('battalion', 'business unit of 300-1000 employees', 'general', 'Unit Type') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('brigade', 'division of 3000-5000 employees', 'general', 'Unit Type') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('company', 'department of 100-200 employees', 'general', 'Unit Type') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('corps', 'enterprise division of 20,000-45,000 employees', 'general', 'Unit Type') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('division', 'organization of 10,000-15,000 employees', 'general', 'Unit Type') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('fireteam', 'small team of 4', 'general', 'Unit Type') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('fleet', 'enterprise operations unit', 'general', 'Unit Type') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('platoon', 'team of 30-50 employees', 'general', 'Unit Type') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('regiment', 'business unit of 1,000-3,000 employees', 'general', 'Unit Type') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('squad', 'team of 8-13 employees', 'general', 'Unit Type') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('squadron', 'operational unit of 100-300 employees', 'general', 'Unit Type') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('strike group', 'combined operations task force', 'general', 'Unit Type') ON CONFLICT DO NOTHING;
INSERT INTO dict_military_jargon (military_term, civilian_equivalent, context, category) VALUES ('wing', 'organization of 1,000-5,000 employees', 'general', 'Unit Type') ON CONFLICT DO NOTHING;

COMMIT;
