-- dict_action_verbs (part c)
-- 239 INSERT statements
-- Run in Supabase SQL Editor


-- BRANCH VALUES: Use lowercase abbreviations ONLY
-- army, navy, usaf, usmc, uscg, ussf, general
-- NEVER use full names like 'Coast Guard' or 'Air Force'
-- Domain context values (logistics, intelligence, cyber, etc.) are also valid
-- Run validate-branch-values.sh before pasting into Supabase

BEGIN;

INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('planned', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('prepared', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('presented', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('prioritized', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('produced', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('programmed', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('proposed', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('provided', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('recommended', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('redesigned', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('reorganized', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('resourced', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('restructured', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('reviewed', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('revised', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('scheduled', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('scoped', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('secured', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('shaped', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('spearheaded', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('specified', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('standardized', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('steered', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('strategized', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('streamlined', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('structured', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('supervised', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('supported', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('systematized', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('tracked', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('transitioned', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('unified', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('upgraded', 'Project Management', 'strong', NULL, '{"management","consulting","PM"}') ON CONFLICT (verb, category) DO NOTHING;
-- Customer Service (72 verbs)
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('accommodated', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('addressed', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('adjusted', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('advised', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('answered', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('anticipated', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('assisted', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('attended', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('built', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('catered', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('clarified', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('collaborated', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('communicated', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('completed', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('confirmed', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('connected', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('consulted', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('contacted', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('contributed', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('coordinated', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('counseled', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('customized', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('delivered', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('demonstrated', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('diagnosed', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('directed', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('educated', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('empathized', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('enabled', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('enhanced', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('ensured', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('exceeded', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('explained', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('facilitated', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('fielded', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('followed up', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('fulfilled', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('greeted', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('guided', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('handled', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('helped', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('improved', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('informed', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('interacted', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('listened', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('maintained', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('managed', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('mediated', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('met', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('navigated', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('negotiated', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('onboarded', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('personalized', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('processed', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('provided', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('recommended', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('reconciled', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('referred', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('registered', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('resolved', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('responded', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('retained', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('satisfied', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('served', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('solved', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('streamlined', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('supported', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('surveyed', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('tailored', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('triaged', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('troubleshot', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('welcomed', 'Customer Service', 'standard', NULL, '{"customer service","sales","support"}') ON CONFLICT (verb, category) DO NOTHING;
-- Creative (77 verbs)
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('abstracted', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('acted', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('adapted', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('authored', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('brainstormed', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('built', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('choreographed', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('composed', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('conceived', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('conceptualized', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('crafted', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('created', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('cultivated', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('customized', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('decorated', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('designed', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('developed', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('devised', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('directed', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('discovered', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('drafted', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('drew', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('edited', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('envisioned', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('established', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('experimented', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('fabricated', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('fashioned', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('filmed', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('formulated', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('founded', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('generated', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('illustrated', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('imagined', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('improvised', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('individualized', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('initiated', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('innovated', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('integrated', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('introduced', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('invented', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('launched', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('made', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('marketed', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('modeled', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('modified', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('molded', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('originated', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('painted', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('performed', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('personalized', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('photographed', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('pioneered', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('planned', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('produced', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('programmed', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('published', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('redesigned', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('refined', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('remodeled', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('rendered', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('renovated', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('revamped', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('revised', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('revitalized', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('rewrote', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('sculpted', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('shaped', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('sketched', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('styled', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('synthesized', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('tailored', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('transformed', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('updated', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('upgraded', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('visualized', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('wrote', 'Creative', 'strong', NULL, '{"design","marketing","media"}') ON CONFLICT (verb, category) DO NOTHING;
-- Quantified Impact (57 verbs)
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('accelerated', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('achieved', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('advanced', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('amplified', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('attained', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('augmented', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('boosted', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('completed', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('conserved', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('consolidated', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('converted', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('cut', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('decreased', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('delivered', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('doubled', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('drove', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('earned', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('eliminated', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('enhanced', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('exceeded', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('expanded', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('expedited', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('gained', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('generated', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('grew', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('halved', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('improved', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('increased', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('launched', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('lowered', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('maximized', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('minimized', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('multiplied', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('netted', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('optimized', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('outpaced', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('outperformed', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('produced', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('quadrupled', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('raised', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('realized', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('recaptured', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('recovered', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('reduced', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('saved', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('scaled', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('shrank', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('slashed', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('streamlined', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('strengthened', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('surpassed', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('sustained', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('transformed', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('trimmed', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('tripled', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('upgraded', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;
INSERT INTO dict_action_verbs (verb, category, strength, avoid_in, best_for) VALUES ('yielded', 'Quantified Impact', 'strong', NULL, '{"any"}') ON CONFLICT (verb, category) DO NOTHING;

COMMIT;
