-- dict_ats_keywords (part b)
-- 105 INSERT statements
-- Run in Supabase SQL Editor


-- BRANCH VALUES: Use lowercase abbreviations ONLY
-- army, navy, usaf, usmc, uscg, ussf, general
-- NEVER use full names like 'Coast Guard' or 'Air Force'
-- Domain context values (logistics, intelligence, cyber, etc.) are also valid
-- Run validate-branch-values.sh before pasting into Supabase

BEGIN;

INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Marketing/Communications', 'PR Specialist', '{"Cision","Meltwater","Muck Rack","Event Planning","Press Conferences","Media Kit"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Marketing/Communications', 'PR Specialist', '{"Thought Leadership","Ghostwriting","Internal Communications","Social Media"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Marketing/Communications', 'Digital Marketing Manager', '{"Digital Marketing","PPC","Display Advertising","Email Marketing","Marketing Automation","Conversion Rate Optimization"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Marketing/Communications', 'Digital Marketing Manager', '{"Google Ads","Facebook Ads","Programmatic","DMP","CDP","Retargeting"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Marketing/Communications', 'Digital Marketing Manager', '{"Landing Pages","UX Optimization","Attribution Modeling","Customer Journey Mapping"}', 'medium') ON CONFLICT DO NOTHING;
-- ----- Industry: Non-Profit -----
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Program Manager (Non-Profit)', '{"Program Management","Grant Management","Outcomes Measurement","Logic Models","Theory of Change","Stakeholder Engagement"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Program Manager (Non-Profit)', '{"Budget Management","Reporting","Compliance","Monitoring and Evaluation","Data Collection"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Program Manager (Non-Profit)', '{"Staff Supervision","Volunteer Management","Community Partnerships","Capacity Building"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Program Manager (Non-Profit)', '{"Strategic Planning","Board Relations","Advocacy","Policy Development"}', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Grant Writer', '{"Grant Writing","Proposal Development","Research","Budget Narrative","LOI","Federal Grants","Foundation Grants"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Grant Writer', '{"Grants.gov","Foundation Directory","Prospect Research","Funder Relations","Reporting"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Grant Writer', '{"Data Analysis","Outcomes Measurement","Storytelling","Editing","Compliance"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Grant Writer', '{"Database Management","Calendar Management","Team Collaboration","Fundraising Strategy"}', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Fundraiser', '{"Fundraising","Donor Relations","Major Gifts","Annual Fund","Capital Campaign","Planned Giving"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Fundraiser', '{"CRM","Raiser''s Edge","Salesforce","DonorPerfect","Event Planning","Direct Mail"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Fundraiser', '{"Prospect Research","Cultivation","Stewardship","Board Engagement","Volunteer Recruitment"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Fundraiser', '{"Marketing","Social Media","Crowdfunding","Corporate Partnerships"}', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Community Outreach Coordinator', '{"Community Engagement","Outreach","Partnership Development","Event Planning","Public Speaking","Cultural Competency"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Community Outreach Coordinator', '{"Needs Assessment","Resource Mapping","Referral Networks","Advocacy","Volunteer Coordination"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Community Outreach Coordinator', '{"Social Media","Newsletter","Flyers","Presentations","Data Collection"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Case Manager', '{"Case Management","Client Assessment","Service Planning","Crisis Intervention","Resource Coordination","Documentation"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Case Manager', '{"Motivational Interviewing","Trauma-Informed Care","Cultural Competency","HIPAA","Confidentiality"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Case Manager', '{"Database Management","Outcome Tracking","Progress Notes","Referrals","Follow-Up"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Case Manager', '{"Supervision","Training","Program Development","Quality Improvement"}', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Volunteer Coordinator', '{"Volunteer Management","Recruitment","Training","Scheduling","Retention","Recognition"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Volunteer Coordinator', '{"Volunteer Management Software","Background Checks","Orientation","Performance Tracking"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Non-Profit', 'Volunteer Coordinator', '{"Event Planning","Community Outreach","Social Media","Partnerships"}', 'medium') ON CONFLICT DO NOTHING;
-- ----- Industry: Telecommunications -----
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'Network Engineer', '{"Networking","TCP/IP","BGP","OSPF","MPLS","Cisco","Juniper","Routing","Switching"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'Network Engineer', '{"SDN","NFV","DWDM","SONET","Fiber Optics","Ethernet","VLAN"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'Network Engineer', '{"Network Monitoring","Troubleshooting","Performance Optimization","Capacity Planning","SolarWinds"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'Network Engineer', '{"Documentation","Vendor Management","Change Management","ITIL"}', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'RF Engineer', '{"RF Design","5G","LTE","4G","Antenna Design","Propagation","Drive Testing","Optimization"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'RF Engineer', '{"ATOLL","Planet","MapInfo","Actix","TEMS","Cell Planning","Coverage Analysis"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'RF Engineer', '{"Interference Mitigation","Capacity Planning","KPI Analysis","Cluster Optimization"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'RF Engineer', '{"Site Selection","Regulatory Compliance","FCC","Environmental Review"}', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'Field Technician', '{"Installation","Maintenance","Troubleshooting","Fiber Optics","Copper","Splicing","OTDR"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'Field Technician', '{"Tower Climbing","Antenna Installation","Microwave","Cable Termination","Testing"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'Field Technician', '{"Safety","OSHA","Fall Protection","CDL","Customer Service"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'Field Technician', '{"Documentation","Inventory","Fleet Vehicle","Time Management"}', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'NOC Analyst', '{"Network Operations","Monitoring","Incident Management","Ticketing","Escalation","SNMP","Syslog"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'NOC Analyst', '{"SolarWinds","Nagios","PRTG","Grafana","Splunk","ServiceNow","ITIL"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'NOC Analyst', '{"Root Cause Analysis","Performance Reporting","SLA Management","Change Management"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'NOC Analyst', '{"Documentation","Runbooks","Training","Shift Handover"}', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'Telecom Project Manager', '{"Project Management","Telecom","Network Deployment","Site Acquisition","Construction Management"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'Telecom Project Manager', '{"MS Project","Budget Management","Vendor Management","Permitting","Regulatory Compliance"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'Telecom Project Manager', '{"5G Deployment","Fiber Build","Small Cell","DAS","Macro Sites"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Telecommunications', 'Telecom Project Manager', '{"Stakeholder Management","Risk Management","Quality Assurance","Closeout"}', 'low') ON CONFLICT DO NOTHING;
-- ----- Industry: Retail/Hospitality -----
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Store Manager', '{"Store Operations","Sales Management","P&L","Inventory Management","Visual Merchandising","Customer Service"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Store Manager', '{"POS Systems","Staff Management","Scheduling","Training","Loss Prevention","Shrinkage"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Store Manager', '{"KPIs","Conversion Rate","Average Transaction","Customer Retention","Loyalty Programs"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Store Manager', '{"Community Events","Local Marketing","Facility Maintenance","Compliance"}', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'District Manager', '{"Multi-Unit Management","Revenue Growth","Operational Excellence","P&L","Strategic Planning"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'District Manager', '{"Performance Management","Talent Development","Store Visits","Action Plans","Benchmarking"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'District Manager', '{"New Store Openings","Remodels","Market Analysis","Competitive Intelligence"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'District Manager', '{"Cross-functional Partnership","Corporate Initiatives","Change Management"}', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Operations Manager (Retail)', '{"Operations Management","Process Improvement","Supply Chain","Distribution","Warehouse","Fulfillment"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Operations Manager (Retail)', '{"WMS","OMS","ERP","Workforce Management","Labor Optimization","Scheduling"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Operations Manager (Retail)', '{"E-Commerce Fulfillment","BOPIS","Omnichannel","Returns Processing"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Customer Service Manager', '{"Customer Service","Call Center","Quality Assurance","Customer Satisfaction","CSAT","NPS","CRM"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Customer Service Manager', '{"Zendesk","Salesforce Service Cloud","Genesys","Workforce Management","Training"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Customer Service Manager', '{"Escalation Management","Process Improvement","Knowledge Base","SLA Management"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Merchandiser', '{"Visual Merchandising","Planograms","Product Placement","Inventory Management","Sales Analysis"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Merchandiser', '{"Space Planning","Category Management","Vendor Relations","Promotional Displays","Seasonal Planning"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Merchandiser', '{"Trend Analysis","Competitive Shopping","Photography","Reporting"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Hotel Manager', '{"Hotel Operations","Revenue Management","Guest Satisfaction","Front Office","Housekeeping","F&B"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Hotel Manager', '{"Opera PMS","STR Reports","Rate Strategy","OTA Management","Staff Training"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Hotel Manager', '{"Sales","Events","Banquets","Catering","Brand Standards","Quality Audits"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Hotel Manager', '{"Community Relations","Sustainability","Renovation Projects","Owner Relations"}', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Restaurant Manager', '{"Food Service Operations","Health Code Compliance","Staff Scheduling","Inventory Control","Cost Control"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Restaurant Manager', '{"POS Systems","Food Safety","ServSafe","Menu Development","Vendor Management"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Retail/Hospitality', 'Restaurant Manager', '{"Customer Satisfaction","Upselling","Labor Cost","Training","Catering"}', 'medium') ON CONFLICT DO NOTHING;
-- ----- Industry: Technology -----
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Technology', 'Site Reliability Engineer', '{"SRE","Reliability","Observability","Incident Management","SLO","SLI","Error Budget","Postmortem"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Technology', 'Site Reliability Engineer', '{"Prometheus","Grafana","PagerDuty","Terraform","Kubernetes","Docker","Linux"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Technology', 'Site Reliability Engineer', '{"Chaos Engineering","Load Testing","Capacity Planning","Automation","Python","Go"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Technology', 'Site Reliability Engineer', '{"Documentation","Runbooks","On-call Rotation","Blameless Culture"}', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Technology', 'Data Engineer', '{"Data Pipelines","ETL","Apache Spark","Apache Kafka","Airflow","SQL","Python","Data Warehousing"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Technology', 'Data Engineer', '{"Snowflake","BigQuery","Redshift","dbt","Data Modeling","Schema Design"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Technology', 'Data Engineer', '{"AWS","GCP","Azure","Docker","CI/CD","Data Quality","Data Governance"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Technology', 'Data Engineer', '{"Documentation","Stakeholder Communication","Cost Optimization","Performance Tuning"}', 'low') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Technology', 'Information Security Manager', '{"Information Security","CISO","Security Strategy","Risk Management","Compliance","NIST","ISO 27001"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Technology', 'Information Security Manager', '{"Security Operations","Incident Response","Vulnerability Management","Penetration Testing","Security Architecture"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Technology', 'Information Security Manager', '{"GRC","SOC 2","PCI DSS","HIPAA Security","Security Awareness Training"}', 'medium') ON CONFLICT DO NOTHING;
-- ----- Industry: Healthcare -----
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Healthcare', 'Dental Hygienist', '{"Dental Prophylaxis","Periodontal Assessment","X-Rays","Patient Education","Infection Control","Scaling"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Healthcare', 'Dental Hygienist', '{"Eaglesoft","Dentrix","Digital Radiography","Sealants","Fluoride Treatment"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Healthcare', 'Dental Hygienist', '{"Patient Communication","Charting","Treatment Planning","Sterilization"}', 'medium') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Healthcare', 'Occupational Therapist', '{"Occupational Therapy","Functional Assessment","Treatment Planning","ADL Training","Adaptive Equipment","Hand Therapy"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Healthcare', 'Occupational Therapist', '{"Cognitive Rehabilitation","Sensory Integration","Splinting","Work Hardening","Ergonomic Assessment"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Healthcare', 'Occupational Therapist', '{"Documentation","Insurance Authorization","Outcome Measures","Evidence-Based Practice"}', 'medium') ON CONFLICT DO NOTHING;
-- ----- Industry: Finance/Banking -----
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Finance/Banking', 'Wealth Manager', '{"Wealth Management","Portfolio Management","Asset Allocation","High Net Worth","Financial Planning","CFA"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Finance/Banking', 'Wealth Manager', '{"Alternative Investments","Tax Optimization","Estate Planning","Trust Services","Bloomberg"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Finance/Banking', 'Wealth Manager', '{"Client Relationship Management","Regulatory Compliance","Fiduciary Duty","Succession Planning"}', 'medium') ON CONFLICT DO NOTHING;
-- ----- Industry: Government/Federal -----
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Government/Federal', 'Grants Management Specialist', '{"Grants Management","Federal Grants","OMB Uniform Guidance","Single Audit","Grants.gov","Compliance"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Government/Federal', 'Grants Management Specialist', '{"Financial Reporting","Monitoring","Closeout","Cost Principles","Allowable Costs"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Government/Federal', 'Grants Management Specialist', '{"Program Evaluation","Risk Assessment","Corrective Action","Technical Assistance"}', 'medium') ON CONFLICT DO NOTHING;
-- ----- Industry: Defense/Aerospace -----
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Defense/Aerospace', 'Satellite Operations', '{"Satellite Operations","TT&C","Orbit Determination","Space Situational Awareness","Ground Segment"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Defense/Aerospace', 'Satellite Operations', '{"STK","MATLAB","Link Budget","Antenna Systems","RF Communications"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Defense/Aerospace', 'Satellite Operations', '{"Anomaly Resolution","Contingency Planning","On-Orbit Testing","Maneuver Planning"}', 'medium') ON CONFLICT DO NOTHING;
-- ----- Industry: Energy/Utilities -----
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Energy/Utilities', 'Grid Operations', '{"Grid Operations","Energy Management System","NERC","Bulk Electric System","System Operator Certification"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Energy/Utilities', 'Grid Operations', '{"SCADA","Real-Time Monitoring","Load Forecasting","Interchange Scheduling","Voltage Regulation"}', 'high') ON CONFLICT DO NOTHING;
-- ----- Industry: Construction -----
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Construction', 'Superintendent', '{"Construction Superintendent","Project Scheduling","Crew Management","Quality Control","Safety Management","Budget Control"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Construction', 'Superintendent', '{"Blueprint Reading","OSHA 30","Subcontractor Coordination","Daily Logs","Punch List Management"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Construction', 'Superintendent', '{"Concrete","Steel","MEP Coordination","Commissioning","Closeout"}', 'medium') ON CONFLICT DO NOTHING;
-- ----- Industry: Logistics/Supply Chain -----
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Logistics/Supply Chain', 'Customs Broker', '{"Customs Brokerage","Import/Export","HTS Classification","Customs Compliance","CBP","Trade Compliance"}', 'critical') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Logistics/Supply Chain', 'Customs Broker', '{"Licensed Customs Broker","ACE","ISF","Free Trade Agreements","Duty Drawback"}', 'high') ON CONFLICT DO NOTHING;
INSERT INTO dict_ats_keywords (industry, role_type, keywords, weight) VALUES ('Logistics/Supply Chain', 'Customs Broker', '{"Tariff Engineering","Valuation","Country of Origin","Bonded Warehouse"}', 'medium') ON CONFLICT DO NOTHING;

COMMIT;
